export const STYLE: { [key: string]: string | number } = {
  HALF_GUTTER: '0.5rem',
  GUTTER: '1rem',
  CONTENT_PADDING: '.75rem',
  SIDER_SIZE: '1.4rem',
  BORDER_RADIUS: '.25rem',

  HEADER_HEIGHT: '8rem',
  HEADER_PHOTO_LIBRARY_HEIGHT: '11rem',
  PRE_LOGIN_HEADER_HEIGHT: '4rem',
  FOOTER_HEIGHT: '4rem',

  SIDER_ITEM_BORDER_RADIUS: '1rem',
  SIDER_ITEM_PADDING_LEFT: '1.6rem',
  SIDER_ITEM_PADDING_RIGHT: '0.8rem',

  TEXT_FONT_SIZE_EXTRA_EXTRA_SMALL: '0.75rem', // 12px
  TEXT_LINE_HEIGHT_EXTRA_EXTRA_SMALL: '0.6rem',
  TEXT_FONT_SIZE_EXTRA_SMALL: '0.875rem', // 14px
  TEXT_LINE_HEIGHT_EXTRA_SMALL: '1.3rem',
  TEXT_FONT_SIZE_SMALL: '1.05rem', // 16.8px
  TEXT_LINE_HEIGHT_SMALL: '1.4rem',
  TEXT_FONT_SIZE_MEDIUM: '1.2rem', // 19.2px
  TEXT_LINE_HEIGHT_MEDIUM: '1.8rem',

  HEADING_FONT_SIZE_EXTRA_SMALL: '1.2rem', // 19.2px
  HEADING_LINE_HEIGHT_EXTRA_SMALL: '1.95rem',
  HEADING_FONT_SIZE_SMALL: '1.332rem', // 21.3px
  HEADING_LINE_HEIGHT_SMALL: '1.95rem',
  HEADING_FONT_SIZE_MEDIUM: '1.5rem', // 24px
  HEADING_LINE_HEIGHT_MEDIUM: '2.1rem',
  HEADING_FONT_SIZE_LARGE: '1.65rem', // 26.4px
  HEADING_LINE_HEIGHT_LARGE: '3.6rem',
  HEADING_FONT_SIZE_EXTRA_SMALL_LARGE: '1.9rem',
  HEADING_FONT_SIZE_EXTRA_LARGE: '2.4rem',
  HEADING_LINE_HEIGHT_EXTRA_LARGE: '3.6rem',
  FONT_SIZE_XXS: '.875rem',
  FONT_SIZE_XS: '.9rem',
  FONT_SIZE_SM: '1.02rem',
  FONT_SIZE_XMD: '1.125rem',
  FONT_SIZE_MD: '1.2rem',
  FONT_SIZE_LG: '1.44rem',
  FONT_SIZE_EL: '1.68rem',

  THUMBNAIL_IMAGE_SIZE: 500,

  SM_SLIDESHOW_IMAGE_DEFAULT_WIDTH: 480,
  SM_SLIDESHOW_IMAGE_DEFAULT_HEIGHT: 270,
  MD_SLIDESHOW_IMAGE_DEFAULT_WIDTH: 960,
  MD_SLIDESHOW_IMAGE_DEFAULT_HEIGHT: 540,
  LG_SLIDESHOW_IMAGE_DEFAULT_WIDTH: 1200,
  LG_SLIDESHOW_IMAGE_DEFAULT_HEIGHT: 675,

  FONT_WEIGHT_LIGHT: '100',
  FONT_WEIGHT_NORMAL: '300',
  FONT_WEIGHT_SEMI_BOLD: '600',
  FONT_WEIGHT_BOLD: '800',

  SLIDESHOW_THUMBNAIL_WIDTH: '290px',
  SLIDESHOW_THUMBNAIL_HEIGHT: '164px',
  SLIDESHOW_PREVIEW_WIDTH: 640, // in pixel
  SLIDESHOW_PREVIEW_HEIGHT: 360, // in pixel

  FIELD_MARGIN: '0 0 1.2rem 0',
  FIELD_MARGIN_BOTTOM: 0.6,

  CARD_PRODUCT_FRAME_GAP: '0.25rem',
  CARD_PRODUCT_BORDER_SIZE: 3, // in pixel
  CARD_PRODUCT_BORDER_SIZE_M: 5,

  IMAGE_LIBRARY_ITEM_WIDTH: 125, // in pixel
}

export const SLIDESHOW_THUMBNAIL_WIDTH_HEIGHT_RATIO =
  parseInt((STYLE.SLIDESHOW_THUMBNAIL_WIDTH as string).replace('px', '')) /
  parseInt((STYLE.SLIDESHOW_THUMBNAIL_HEIGHT as string).replace('px', ''))

STYLE.TEXT_EXTRA_EXTRA_SMALL = `
  font-size: ${STYLE.TEXT_FONT_SIZE_EXTRA_EXTRA_SMALL};
  line-height: ${STYLE.TEXT_LINE_HEIGHT_EXTRA_EXTRA_SMALL};
`

STYLE.TEXT_EXTRA_SMALL = `
  font-size: ${STYLE.TEXT_FONT_SIZE_EXTRA_SMALL};
  line-height: ${STYLE.TEXT_LINE_HEIGHT_EXTRA_SMALL};
`

STYLE.TEXT_SMALL = `
  font-size: ${STYLE.TEXT_FONT_SIZE_SMALL};
  line-height: ${STYLE.TEXT_LINE_HEIGHT_SMALL};
`
STYLE.TEXT_MEDIUM = `
  font-size: ${STYLE.TEXT_FONT_SIZE_MEDIUM};
  line-height: ${STYLE.TEXT_LINE_HEIGHT_MEDIUM};
`
STYLE.HEADING_EXTRA_SMALL = `
  font-size: ${STYLE.HEADING_FONT_SIZE_EXTRA_SMALL};
  line-height: ${STYLE.HEADING_LINE_HEIGHT_EXTRA_SMALL};
`
STYLE.HEADING_SMALL = `
  font-size: ${STYLE.HEADING_FONT_SIZE_SMALL};
  line-height: ${STYLE.HEADING_LINE_HEIGHT_SMALL};
`
STYLE.HEADING_MEDIUM = `
  font-size: ${STYLE.HEADING_FONT_SIZE_MEDIUM};
  line-height: ${STYLE.HEADING_LINE_HEIGHT_MEDIUM};
`
STYLE.HEADING_LARGE = `
  font-size: ${STYLE.HEADING_FONT_SIZE_LARGE};
  line-height: ${STYLE.HEADING_LINE_HEIGHT_LARGE};
`
STYLE.HEADING_EXTRA_LARGE = `
  font-size: ${STYLE.HEADING_FONT_SIZE_EXTRA_LARGE};
  line-height: ${STYLE.HEADING_LINE_HEIGHT_EXTRA_LARGE};
`

STYLE.FIELD_STYLE = `
  margin: ${STYLE.FIELD_MARGIN}
`

STYLE.BOX_SHADOW_SIZE = '0 1px 4px'
STYLE.BOTTOM_BAR_HEIGHT = 60

export const COLOR: { [key: string]: string } = {
  DIANNE_BLUE: '#193B44',
  SCOOTER_BLUE: '#3DC3D0',
  TINT_TEAL_BLUE: '#D9F2F4',
  GEEK_BLUE: '#2F54EB',
  TEAL_BLUE: '#41BCC8',
  SHALLOW_GREY: '#E8E8E8',
  CORNFLOWER_BLUE: '#76258a',
  BLACK: '#0A0A0A',
  DOVE_GREY: '#999',
  SUPER_DARK_GREY: '#18191A',
  GREY: '#C2C2C2',
  BEIGE_GREY: '#F6F4F1',
  NEUTRAL_GREY: '#616161',
  LITE_GREY: '#F1F1F1',
  SUPER_LITE_GREY: '#F9F9F9',
  WIDE_SAND_GREY: '#F5F5F5',
  ISABELLINE: '#F6F2E9',
  WHITE: '#fff',
  ABBEY_PURPLE: '#7A79F9',
  RED: '#d0021b',
  MAGENTA: '#B9346F',
  REGAL_BLUE: '#00416B',
  LIGHT_RED: '#FF4D4F',
  GREEN: '#03AC13',
  CYAN: '#13C2C2',
  PURPLE: '#722ed1',
  VOLCANO: '#FA541C',
  ORANGE: '#faad14',
  SLATE_GREY: '#717E8E',
  // new reskin colour:
  DARK_BLUE: '#9e21bd',
  CORE_PURPLE: '#9e21bd',
  CORE_PURPLE_10: '#ECDFEF',
  CORE_PURPLE_30: '#DAB5E4',
  CORE_PURPLE_60: '#C176D3',
  CORE_PURPLE_80: '#AF4BC8',
  PASTEL_BLUE: '#EDE0F0', // ECDFEF
  GREY_BACKGROUND: '#F3F3F3',
  PURE_BLACK: '#00000',
  PURPLE_HIGHLIGHTS: '#8385ff',
  SHADOW_GREY: '#EAEAEE',
  SHADOW_GREEN: '#D9F2F3',
  DARK_GREEN_BLACK: '#1a343b',
  PRE_LOGGED_BACKGROUND_COLOR: '#EDE0F0',
  ANTD_INPUT_ERROR_RED_COLOR: '#ff4d4f',
  SHALOW_PINK: '#f9d8da',
  DEEP_PINK: '#e2a9ae',
  WARM_GREY_WHITE_BG: '#F6F4F1',
  LIGHT_GREY: '#d3d3d3',
}

COLOR.PRIMARY = COLOR.DARK_GREEN_BLACK
COLOR.PRIMARY_BACKGROUND_COLOR = COLOR.PASTEL_BLUE
COLOR.PANEL_BACKGROUND_COLOR = '#f6f4f1'
COLOR.HOVER_BORDER_COLOR = COLOR.CORE_PURPLE
COLOR.TEXT_COLOR = COLOR.DARK_GREEN_BLACK
COLOR.BORDER_COLOR = '#D8D8D8'
COLOR.TEXT_DISABLED_COLOR = COLOR.DOVE_GREY
COLOR.LINK_HOVER_COLOR = COLOR.SCOOTER_BLUE
COLOR.SIDER_ITEM_HOVER_BACKGROUND_COLOR = COLOR.LITE_GREY
COLOR.WARNING = COLOR.RED
COLOR.INFO = COLOR.ORANGE
COLOR.SUCCESS = COLOR.SCOOTER_BLUE
COLOR.HINT_TEXT_COLOR = COLOR.GREY
COLOR.ERROR = COLOR.ANTD_INPUT_ERROR_RED_COLOR
COLOR.BOX_SHADOW_COLOR = 'rgba(0,21,41,0.25)'
