export enum EulogiseEndpoint {
  ALL_RESOURCES = '/v2/admin/cases/{caseId}/resources',
  ALL_SHARE_RESOURCES = '/v2/cases/{caseId}/shares/resources',
  FETCH_CONNECTIONS_BY_CASE_ID = '/v2/connections/:caseId',
  UPDATE_PRODUCT_BY_ID = '/v2/admin/products/{product}/{productId}',
  UNLOCK_PRODUCT_BY_ID = '/v2/admin/products/{product}/{productId}/unlock',
  FIND_RESOURCE = '/v2/old/resource/find',
  SAVE_RESOURCE = '/v2/old/resource/save',
  SHARE_BY_CASE_ID = `/v2/cases/{caseId}/shares`,
  GENERATE_RESOURCE = '/v2/products/{productType}/{productId}/generate',
  FACE_DETECTION_BY_CASE_ID = `/v2/assets/cases/{caseId}/face-detection`,
  SEND_INVITE = '/v2/old/resource/invite/send',
  SEND_WELCOME_INVITE = '/v2/users/{userId}/sendInvite',
  REMOVE_RESOURCE = '/v2/old/resource/remove',
  REMOVE_MULTIPLE_RESOURCE = '/v2/old/resource/remove-multiple',
  REMOVE_IMAGE_BACKGROUND = '/v2/old/resource/removeImageBackground',
  SHADOW_TOKEN_RESOURCE = '/v2/old/resource/user/shadow-token',
  ACCOUNT_SIGN_IN = '/v2/old/account/sign/in',
  ACCOUNT_SIGN_UP = '/v2/old/account/sign/up',
  ACCOUNT_SIGN_UP_AS_CLIENT = '/v2/old/account/sign/up-customer-as-client',
  ACCOUNT_CHECK = '/v2/old/account/sign/check',
  ACCOUNT_SAVE = '/v2/old/account/save',
  ACCOUNT_VERIFY_EMAIL = '/v2/old/account/verify-email',
  FORGOT_PASSWORD = '/v2/old/account/forgot-password',
  RESET_PASSWORD = '/v2/old/account/reset-password',
  ACCOUNT_DELETE = '/v2/users/self/delete',
  CREATE_PAYMENT = '/v2/old/payment/create',
  ACCOUNT_SIGN_UP_FUNERAL_DIRECTOR_AS_ADMIN = '/v2/old/account/sign/up-funeral-director-as-admin',
  ACCOUNT_SIGN_UP_CO_EDITOR = '/v2/old/account/sign/up-co-editor',
  GENERATE_PRE_SIGNED_URL = '/v2/old/resource/asset/generatePreSignedUrl',

  // These are pages not endpoints
  DASHBOARD = '/admin/dashboard',
  CLIENT_DASHBOARD = '/admin/client/cases',
  PHOTO_LIBRARY = '/admin/photoLibrary',
  BACKGROUND_IMAGE_LIBRARY = '/admin/backgroundImageLibrary',
  EULOGIZE_ADMIN_CREATE_EDIT_NEW_CLIENT = '/eulogizeAdmin/create/create-client/',
  EULOGIZE_SLIDESHOW_PREVIEW_PAGE = '/admin/slideshows-preview',
  EULOGIZE_PRINTING_DETAILS_PAGE = '/admin/checkout/printing-details/',
}
