import { ICardProductIcon } from '@eulogise/core'

export const EULOGISE_CARD_PRODUCT_ICONS: Array<ICardProductIcon> = [
  {
    id: 'Christian',
  },
  { id: 'ChristianCross' },
  { id: 'Cross' },
  { id: 'Cross2' },
  { id: 'Cross3' },
  { id: 'Dove' },
  { id: 'Dove2' },
  { id: 'Fish' },
  { id: 'Flower' },
  { id: 'GolfFlag' },
  { id: 'Heart' },
  { id: 'Heart2' },
  { id: 'Ichthus' },
  { id: 'Jewish' },
  { id: 'Jewish2' },
  { id: 'Leaf' },
  { id: 'Leaf2' },
  { id: 'Leaf3' },
  { id: 'MusicNote' },
  { id: 'MusicNote2' },
  { id: 'Muslim' },
  { id: 'Ribbon' },
  { id: 'SailBoat' },
  { id: 'Star' },
  { id: 'Star2' },
  { id: 'Star3' },
  { id: 'Tree' },
  { id: 'Tree2' },
  { id: 'YingYang' },
]
