import {
  CardProductPageSize,
  EulogiseCountry,
  ValidPhotobookCheckoutSize,
} from '@eulogise/core'

export interface IPPhotoBookPricing {
  BASE_PRICE: number
  EXTRA_PAGE_PRICE: number
  MIN_EXTRA_PAGES: number
  VEGAN_LEATHER_ADDON: number
  BASE_PAGE_COUNT: number
}

export const NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT: IPPhotoBookPricing = {
  BASE_PRICE: 999,
  EXTRA_PAGE_PRICE: 99,
  MIN_EXTRA_PAGES: 99,
  VEGAN_LEATHER_ADDON: 999,
  BASE_PAGE_COUNT: 999,
}

export const PHOTOBOOK_PRICING: Record<
  ValidPhotobookCheckoutSize,
  Record<EulogiseCountry, IPPhotoBookPricing>
> = {
  [CardProductPageSize.PHOTOBOOK_MILK_CLASSIC_MEDIUM]: {
    [EulogiseCountry.AUSTRALIA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.UNITED_STATES]: {
      BASE_PRICE: 44.0,
      EXTRA_PAGE_PRICE: 0.8,
      MIN_EXTRA_PAGES: 2,
      VEGAN_LEATHER_ADDON: 11.0,
      BASE_PAGE_COUNT: 24,
    },
    [EulogiseCountry.EUROPEAN_UNION]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.UNITED_KINGDOM]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.CHILE]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.THE_PHILIPPINES]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.REST_OF_THE_WOLRD]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.CANADA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
  },
  [CardProductPageSize.PHOTOBOOK_MILK_CLASSIC_LARGE]: {
    [EulogiseCountry.AUSTRALIA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.UNITED_STATES]: {
      BASE_PRICE: 96.0,
      EXTRA_PAGE_PRICE: 1.1,
      MIN_EXTRA_PAGES: 2,
      VEGAN_LEATHER_ADDON: 11.0,
      BASE_PAGE_COUNT: 24,
    },
    [EulogiseCountry.EUROPEAN_UNION]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.UNITED_KINGDOM]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.CHILE]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.THE_PHILIPPINES]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.REST_OF_THE_WOLRD]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.CANADA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
  },
  [CardProductPageSize.PHOTOBOOK_MILK_PREMIUM_MEDIUM]: {
    [EulogiseCountry.AUSTRALIA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.UNITED_STATES]: {
      BASE_PRICE: 68.0,
      EXTRA_PAGE_PRICE: 1.8,
      MIN_EXTRA_PAGES: 4,
      VEGAN_LEATHER_ADDON: 11.0,
      BASE_PAGE_COUNT: 24,
    },
    [EulogiseCountry.EUROPEAN_UNION]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.UNITED_KINGDOM]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.CHILE]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.THE_PHILIPPINES]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.REST_OF_THE_WOLRD]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.CANADA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
  },
  [CardProductPageSize.PHOTOBOOK_MILK_PREMIUM_LARGE]: {
    [EulogiseCountry.AUSTRALIA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.UNITED_STATES]: {
      BASE_PRICE: 135.0,
      EXTRA_PAGE_PRICE: 2.5,
      MIN_EXTRA_PAGES: 4,
      VEGAN_LEATHER_ADDON: 17.0,
      BASE_PAGE_COUNT: 24,
    },
    [EulogiseCountry.EUROPEAN_UNION]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.UNITED_KINGDOM]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.CHILE]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.THE_PHILIPPINES]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.REST_OF_THE_WOLRD]:
      NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
    [EulogiseCountry.CANADA]: NOT_APPLICABLE_PHOTO_BOOK_BASE_PRICE_OBJECT,
  },
}
