import {
  EulogizePrintingProductsPaperTypes,
  IPrintingPaperDefinition,
  EulogiseCardProducts,
  EulogiseCountry,
} from '@eulogise/core'
import { EulogiseClientConfig } from './EulogiseClientConfig'

export const NON_APPLICTABLE_PAPER_PRICE = 999

const NOT_APPLICABLE_PAPER_PRICE_LIST = {
  0: NON_APPLICTABLE_PAPER_PRICE,
  20: NON_APPLICTABLE_PAPER_PRICE,
  40: NON_APPLICTABLE_PAPER_PRICE,
  60: NON_APPLICTABLE_PAPER_PRICE,
  80: NON_APPLICTABLE_PAPER_PRICE,
  100: NON_APPLICTABLE_PAPER_PRICE,
  120: NON_APPLICTABLE_PAPER_PRICE,
  140: NON_APPLICTABLE_PAPER_PRICE,
  160: NON_APPLICTABLE_PAPER_PRICE,
  180: NON_APPLICTABLE_PAPER_PRICE,
  200: NON_APPLICTABLE_PAPER_PRICE,
}

export const EulogizePrintingProductsPaperTypeDefinition: Record<
  EulogizePrintingProductsPaperTypes,
  IPrintingPaperDefinition
> = {
  [EulogizePrintingProductsPaperTypes.SMOOTH_MATTE]: {
    key: EulogizePrintingProductsPaperTypes.SMOOTH_MATTE,
    displayName: EulogizePrintingProductsPaperTypes.SMOOTH_MATTE,
    description: `A thick and smooth card stock, Matte's texture is soft to the touch with a clean, crisp finish.`,
    weight: 130,
    weightUnit: 'lb',
    thickness: '16 point',
    // @ts-ignore
    perPaperUnitPrice: {
      [EulogiseCardProducts.BOOKLET]: {
        [EulogiseCountry.AUSTRALIA]: {
          0: 0,
          20: 7.63,
          40: 4.69,
          60: 3.48,
          80: 2.87,
          100: 2.51,
          120: 2.32,
          140: 2.19,
          160: 1.96,
          180: 1.86,
          200: 1.74,
        },
        [EulogiseCountry.UNITED_STATES]: {
          0: 0,
          20: 5.45,
          40: 3.35,
          60: 2.48,
          80: 2.05,
          100: 1.79,
          120: 1.66,
          140: 1.56,
          160: 1.4,
          180: 1.33,
          200: 1.25,
        },
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: {
          0: 0,
          20: 7.14,
          40: 4.39,
          60: 3.25,
          80: 2.69,
          100: 2.34,
          120: 2.17,
          140: 2.05,
          160: 1.83,
          180: 1.74,
          200: 1.63,
        },
      },
      [EulogiseCardProducts.BOOKMARK]: {
        [EulogiseCountry.AUSTRALIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_STATES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
      },
      [EulogiseCardProducts.SIDED_CARD]: {
        [EulogiseCountry.AUSTRALIA]: {
          0: 0,
          20: 6.1,
          40: 3.75,
          60: 2.78,
          80: 2.3,
          100: 2.0,
          120: 1.86,
          140: 1.75,
          160: 1.57,
          180: 1.49,
          200: 1.39,
        },
        [EulogiseCountry.UNITED_STATES]: {
          0: 0,
          20: 4.36,
          40: 2.68,
          60: 1.99,
          80: 1.64,
          100: 1.43,
          120: 1.33,
          140: 1.25,
          160: 1.12,
          180: 1.06,
          200: 1.0,
        },
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: {
          0: 0,
          20: 5.71,
          40: 3.51,
          60: 2.6,
          80: 2.15,
          100: 1.88,
          120: 1.74,
          140: 1.64,
          160: 1.47,
          180: 1.39,
          200: 1.3,
        },
      },
      [EulogiseCardProducts.THANK_YOU_CARD]: {
        [EulogiseCountry.AUSTRALIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_STATES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
      },
      [EulogiseCardProducts.TV_WELCOME_SCREEN]: {
        [EulogiseCountry.AUSTRALIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_STATES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: {
          0: 0,
          20: 5.71,
          40: 3.51,
          60: 2.6,
          80: 2.15,
          100: 1.88,
          120: 1.74,
          140: 1.64,
          160: 1.47,
          180: 1.39,
          200: 1.3,
        },
      },
    },
    imageUrl: `${EulogiseClientConfig.AWS_S3_URL}/printingPaperTypes/smooth-matte-1.png`,
    appliedProducts: [
      EulogiseCardProducts.BOOKLET,
      EulogiseCardProducts.SIDED_CARD,
      EulogiseCardProducts.TV_WELCOME_SCREEN,
    ],
  },
  [EulogizePrintingProductsPaperTypes.SHINY_GLOSS]: {
    key: EulogizePrintingProductsPaperTypes.SHINY_GLOSS,
    displayName: EulogizePrintingProductsPaperTypes.SHINY_GLOSS,
    description:
      'Ideal for photo-heavy designs with a color vibrancy that will make your design pop.',
    weight: 130,
    weightUnit: 'lb',
    thickness: '16 point',
    // @ts-ignore
    perPaperUnitPrice: {
      [EulogiseCardProducts.BOOKLET]: {
        [EulogiseCountry.AUSTRALIA]: {
          0: 0,
          20: 7.63,
          40: 4.69,
          60: 3.48,
          80: 2.87,
          100: 2.51,
          120: 2.32,
          140: 2.19,
          160: 1.96,
          180: 1.86,
          200: 1.74,
        },
        [EulogiseCountry.UNITED_STATES]: {
          0: 0,
          20: 5.45,
          40: 3.35,
          60: 2.48,
          80: 2.05,
          100: 1.79,
          120: 1.66,
          140: 1.56,
          160: 1.4,
          180: 1.33,
          200: 1.25,
        },
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: {
          0: 0,
          20: 7.14,
          40: 4.39,
          60: 3.25,
          80: 2.69,
          100: 2.34,
          120: 2.17,
          140: 2.05,
          160: 1.83,
          180: 1.74,
          200: 1.63,
        },
      },
      [EulogiseCardProducts.BOOKMARK]: {
        [EulogiseCountry.AUSTRALIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_STATES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
      },
      [EulogiseCardProducts.SIDED_CARD]: {
        [EulogiseCountry.AUSTRALIA]: {
          0: 0,
          20: 6.1,
          40: 3.75,
          60: 2.78,
          80: 2.3,
          100: 2.0,
          120: 1.86,
          140: 1.75,
          160: 1.57,
          180: 1.49,
          200: 1.39,
        },
        [EulogiseCountry.UNITED_STATES]: {
          0: 0,
          20: 4.36,
          40: 2.68,
          60: 1.99,
          80: 1.64,
          100: 1.43,
          120: 1.33,
          140: 1.25,
          160: 1.12,
          180: 1.06,
          200: 1.0,
        },
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: {
          0: 0,
          20: 5.71,
          40: 3.51,
          60: 2.6,
          80: 2.15,
          100: 1.88,
          120: 1.74,
          140: 1.64,
          160: 1.47,
          180: 1.39,
          200: 1.3,
        },
      },
      [EulogiseCardProducts.THANK_YOU_CARD]: {
        [EulogiseCountry.AUSTRALIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_STATES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
      },
      [EulogiseCardProducts.TV_WELCOME_SCREEN]: {
        [EulogiseCountry.AUSTRALIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_STATES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
      },
    },
    imageUrl: `${EulogiseClientConfig.AWS_S3_URL}/printingPaperTypes/shiny-gloss-1.png`,
    appliedProducts: [
      EulogiseCardProducts.BOOKLET,
      EulogiseCardProducts.SIDED_CARD,
      EulogiseCardProducts.TV_WELCOME_SCREEN,
    ],
  },
  [EulogizePrintingProductsPaperTypes.PREMIUM_LINEN]: {
    key: EulogizePrintingProductsPaperTypes.PREMIUM_LINEN,
    displayName: EulogizePrintingProductsPaperTypes.PREMIUM_LINEN,
    description:
      'The beautiful texture of embossed linen creates a subtle, yet refined impression.',
    weight: 100,
    weightUnit: 'lb',
    thickness: '12 point',
    // @ts-ignore
    perPaperUnitPrice: {
      [EulogiseCardProducts.BOOKLET]: {
        [EulogiseCountry.AUSTRALIA]: {
          0: 0,
          20: 8.33,
          40: 5.39,
          60: 4.18,
          80: 3.57,
          100: 3.21,
          120: 3.02,
          140: 2.89,
          160: 2.66,
          180: 2.56,
          200: 2.44,
        },
        [EulogiseCountry.UNITED_STATES]: {
          0: 0,
          20: 6.15,
          40: 4.05,
          60: 3.18,
          80: 2.75,
          100: 2.49,
          120: 2.36,
          140: 2.26,
          160: 2.1,
          180: 2.03,
          200: 1.95,
        },
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: {
          0: 0,
          20: 7.84,
          40: 5.09,
          60: 3.95,
          80: 3.39,
          100: 3.04,
          120: 2.87,
          140: 2.75,
          160: 2.53,
          180: 2.44,
          200: 2.33,
        },
      },
      [EulogiseCardProducts.BOOKMARK]: {
        [EulogiseCountry.AUSTRALIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_STATES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
      },
      [EulogiseCardProducts.SIDED_CARD]: {
        [EulogiseCountry.AUSTRALIA]: {
          0: 0,
          20: 6.45,
          40: 4.1,
          60: 3.13,
          80: 2.65,
          100: 2.35,
          120: 2.21,
          140: 2.1,
          160: 1.92,
          180: 1.84,
          200: 1.74,
        },
        [EulogiseCountry.UNITED_STATES]: {
          0: 0,
          20: 4.71,
          40: 3.03,
          60: 2.34,
          80: 1.99,
          100: 1.78,
          120: 1.68,
          140: 1.6,
          160: 1.47,
          180: 1.41,
          200: 1.35,
        },
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: {
          0: 0,
          20: 6.06,
          40: 3.86,
          60: 2.95,
          80: 2.5,
          100: 2.23,
          120: 2.09,
          140: 1.99,
          160: 1.82,
          180: 1.74,
          200: 1.65,
        },
      },
      [EulogiseCardProducts.THANK_YOU_CARD]: {
        [EulogiseCountry.AUSTRALIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_STATES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
      },
      [EulogiseCardProducts.TV_WELCOME_SCREEN]: {
        [EulogiseCountry.AUSTRALIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_STATES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.EUROPEAN_UNION]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.UNITED_KINGDOM]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CHILE]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COLOMBIA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.COSTA_RICA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.MEXICO]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.NEW_ZEALAND]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.PANAMA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.GUATEMALA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_DOMINICAN_REPUBLIC]:
          NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.THE_PHILIPPINES]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.REST_OF_THE_WOLRD]: NOT_APPLICABLE_PAPER_PRICE_LIST,
        [EulogiseCountry.CANADA]: NOT_APPLICABLE_PAPER_PRICE_LIST,
      },
    },
    imageUrl: `${EulogiseClientConfig.AWS_S3_URL}/printingPaperTypes/premium-linen-1.png`,
    appliedProducts: [
      EulogiseCardProducts.BOOKLET,
      EulogiseCardProducts.SIDED_CARD,
      EulogiseCardProducts.TV_WELCOME_SCREEN,
    ],
  },
}
