# this is deprecated. For UI buildspec.yml please refer to buildspec.ui.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing Yarn...
      - npm install -g yarn

  pre_build:
    commands:
      # install and build libraries
      - echo Installing and building libraries
      - yarn installAndBuild
      - echo 💡 Loading UI env from SSM
      - node packages/eulogise-client/scripts/load-ssm-env.js --env ${ENVIRONMENT} --path "/eulogise/client/${ENVIRONMENT}"
      - export BUGSNAG_API_KEY=${BUGSNAG_API_KEY:-$(node packages/eulogise-client/scripts/read-env-value.js --path packages/eulogise-client/environments/.env.${ENVIRONMENT} --key BUGSNAG_API_KEY)}
      - echo ✅ UI env loaded
      # build
      - echo Build UI
      - yarn build:ui:${ENVIRONMENT}
  post_build:
    commands:
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - aws s3 cp packages/eulogise-client/public s3://${S3_BUCKET} --recursive
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths '/*'
