export const GENERATOR_CONFIG = {
  SLACK_WEBHOOK_URL: process.env.SLACK_WEBHOOK_URL,
  ENABLE_HTML_GENERATION: process.env.ENABLE_HTML_GENERATION === 'true',
  VIDEO_OUTPUT_SIZE: process.env.VIDEO_OUTPUT_SIZE || '1280x720',
  ENABLE_GENERATOR_CLEAN_UP_SCREENSHOTS:
    process.env.ENABLE_GENERATOR_CLEAN_UP_SCREENSHOTS === 'true',
  NODE_ENV: process.env.NODE_ENV,
  AWS_REGION: process.env.AWS_REGION,
  AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY || process.env.XAWS_ACCESS_KEY,
  AWS_SECRET_KEY: process.env.AWS_SECRET_KEY || process.env.XAWS_SECRET_KEY,
  AWS_S3_BUCKET: process.env.AWS_S3_BUCKET || process.env.XAWS_S3_BUCKET,
  AWS_S3_URL: process.env.AWS_S3_URL || process.env.XAWS_S3_URL,
  AWS_S3_URL_WITHOUT_CDN: process.env.XAWS_S3_URL_WITHOUT_CDN,
  AWS_CLOUD_FRONT_MEDIA_DISTRIBUTION_ID:
    process.env.XAWS_CLOUDFRONT_MEDIA_DISTRIBUTION_ID,
  XAWS_ACCESS_KEY: process.env.XAWS_ACCESS_KEY,
  XAWS_SECRET_KEY: process.env.XAWS_SECRET_KEY,
  XAWS_S3_BUCKET: process.env.XAWS_S3_BUCKET,
  XAWS_REGION: process.env.XAWS_REGION,
  FILESTACK_CDN: process.env.FILESTACK_CDN,
  API_ACCESS_KEY: process.env.API_ACCESS_KEY,
  API_SECRET_KEY: process.env.API_SECRET_KEY,
  API_URL: process.env.API_URL,
  FFMPEG_PATH: process.env.FFMPEG_PATH,
  GHOSTSCRIPT_PATH: process.env.GHOSTSCRIPT_PATH,
  FONTS_PATH: process.env.FONTS_PATH,
  GENERATOR_MASTER_SLIDESHOW_PROCESS_FN:
    process.env.GENERATOR_MASTER_SLIDESHOW_PROCESS_FN,
  GENERATOR_CAPTURE_SCREENSHOT_PROCESS_FN:
    process.env.GENERATOR_CAPTURE_SCREENSHOT_PROCESS_FN,
  GENERATOR_PDF_GENERATION_PROCESS_FN:
    process.env.GENERATOR_PDF_GENERATION_PROCESS_FN,
  GENERATOR_CONVERT_TO_PRINTABLE_PDF_PROCESS_FN:
    process.env.GENERATOR_CONVERT_TO_PRINTABLE_PDF_PROCESS_FN,
  GENERATOR_CARD_PRODUCT_SINGLE_SCREENSHOT_PROCESS_FN:
    process.env.GENERATOR_CARD_PRODUCT_SINGLE_SCREENSHOT_PROCESS_FN,
  GENERATOR_PRODUCT_THUMBNAIL_GENERATION_PROCESS_FN:
    process.env.GENERATOR_PRODUCT_THUMBNAIL_GENERATION_PROCESS_FN,
  GENERATOR_CAPTURE_SCREENSHOT_TRIGGER_FN:
    process.env.GENERATOR_CAPTURE_SCREENSHOT_TRIGGER_FN,
  GENERATOR_MASTER_VIDEO_GENERATION_PROCESS_FN:
    process.env.GENERATOR_MASTER_VIDEO_GENERATION_PROCESS_FN,
  GENERATOR_SLAVE_VIDEO_BLOCK_GENERATION_PROCESS_FN:
    process.env.GENERATOR_SLAVE_VIDEO_BLOCK_GENERATION_PROCESS_FN,
  GENERATOR_SLAVE_FINALISE_VIDEO_PROCESS_FN:
    process.env.GENERATOR_SLAVE_FINALISE_VIDEO_PROCESS_FN,
  GENERATOR_BACKGROUND_IMAGE_PROCESS_FN:
    process.env.GENERATOR_BACKGROUND_IMAGE_PROCESS_FN,
  GENERATOR_EDITED_BACKGROUND_IMAGE_PROCESS_FN:
    process.env.GENERATOR_EDITED_BACKGROUND_IMAGE_PROCESS_FN,
  AWS_LAMBDA_ENDPOINT: process.env.XAWS_LAMBDA_ENDPOINT,
  PUPPETEER_FILE_FORMAT: 'jpg',
  isLambdaGenerateSlideshow:
    process.env.IS_LAMBDA_GENERATE_SLIDESHOW === 'true',
  CHROME_EXECUTION_PATH: process.env.CHROME_EXECUTION_PATH,
  DESIGN_SYSTEM_URL: process.env.DESIGN_SYSTEM_URL,
  TMP_DIR: process.env.TMP_DIR,
  NO_OF_TRIGGERS: 75,
}
