import { IEulogiseClient, IEulogiseUser } from './Resource.types'
import { ICase, IPortalCaseResponseItem } from './Case.types'
import { IInvoice } from './Invoice.types'
import { EulogiseProduct } from './Eulogise.types'
import { ICardProductData } from './CardProduct.types'

export enum AdminActionTypes {
  REEDIT_PRODUCT = 'REEDIT_PRODUCT',
  REEDIT_PRODUCT_SUCCESS = 'REEDIT_PRODUCT_SUCCESS',
  REEDIT_PRODUCT_FAILED = 'REEDIT_PRODUCT_FAILED',
  ADMIN_CASE_SEARCH = 'ADMIN_CASE_SEARCH',
  ADMIN_CASE_SEARCH_SUCCESS = 'ADMIN_CASE_SEARCH_SUCCESS',
  ADMIN_CASE_SEARCH_FAILED = 'ADMIN_CASE_SEARCH_FAILED',
  FETCH_FUNERAL_DIRECTORS_BY_CASE_ID = 'FETCH_FUNERAL_DIRECTORS_BY_CASE_ID',
  FETCH_FUNERAL_DIRECTORS_BY_CASE_ID_SUCCESS = 'FETCH_FUNERAL_DIRECTORS_BY_CASE_ID_SUCCESS',
  FETCH_FUNERAL_DIRECTORS_BY_CASE_ID_FAILED = 'FETCH_FUNERAL_DIRECTORS_BY_CASE_ID_FAILED',
  ASSIGN_FUNERAL_DIRECTOR = 'ASSIGN_FUNERAL_DIRECTOR',
  ASSIGN_FUNERAL_DIRECTOR_SUCCESS = 'ASSIGN_FUNERAL_DIRECTOR_SUCCESS',
  ASSIGN_FUNERAL_DIRECTOR_FAILED = 'ASSIGN_FUNERAL_DIRECTOR_FAILED',
  UPDATE_USER_ROLE = 'UPDATE_USER_ROLE',
  UPDATE_USER_ROLE_SUCCESS = 'UPDATE_USER_ROLE_SUCCESS',
  UPDATE_USER_ROLE_FAILED = 'UPDATE_USER_ROLE_FAILED',
  FETCH_USER_BY_USER_ID = 'FETCH_USER_BY_USER_ID',
  FETCH_USER_BY_USER_ID_SUCCESS = 'FETCH_USER_BY_USER_ID_SUCCESS',
  FETCH_USER_BY_USER_ID_FAILED = 'FETCH_USER_BY_USER_ID_FAILED',
  UPDATE_ADMIN_CASE_BY_ID = 'UPDATE_ADMIN_CASE_BY_ID',
  UPDATE_ADMIN_CASE_BY_ID_SUCCESS = 'UPDATE_ADMIN_CASE_BY_ID_SUCCESS',
  UPDATE_ADMIN_CASE_BY_ID_FAILED = 'UPDATE_ADMIN_CASE_BY_ID_FAILED',
  UPDATE_CLIENT_BY_CLIENT_ID = 'UPDATE_CLIENT_BY_CLIENT_ID',
  UPDATE_CLIENT_BY_CLIENT_ID_SUCCESS = 'UPDATE_CLIENT_BY_CLIENT_ID_SUCCESS',
  UPDATE_CLIENT_BY_CLIENT_ID_FAILED = 'UPDATE_CLIENT_BY_CLIENT_ID_FAILED',
  REMOVE_FUNERAL_DIRECTORY_FROM_CLIENT = 'REMOVE_FUNERAL_DIRECTORY_FROM_CLIENT',
  REMOVE_FUNERAL_DIRECTORY_FROM_CLIENT_SUCCESS = 'REMOVE_FUNERAL_DIRECTORY_FROM_CLIENT_SUCCESS',
  REMOVE_FUNERAL_DIRECTORY_FROM_CLIENT_FAILED = 'REMOVE_FUNERAL_DIRECTORY_FROM_CLIENT_FAILED',
  FETCH_USERS_BY_CLIENT_ID = 'FETCH_USERS_BY_CLIENT_ID',
  FETCH_USERS_BY_CLIENT_ID_SUCCESS = 'FETCH_USERS_BY_CLIENT_ID_SUCCESS',
  FETCH_USERS_BY_CLIENT_ID_FAILED = 'FETCH_USERS_BY_CLIENT_ID_FAILED',
  ADD_NO_OF_IMAGES_TO_ADMIN_BY_CASE_ID = 'ADD_NO_OF_IMAGES_TO_ADMIN_BY_CASE_ID',
  UPDATE_PRODUCT_BY_ID = 'UPDATE_PRODUCT_BY_ID',
  UPDATE_PRODUCT_BY_ID_SUCCESS = 'UPDATE_PRODUCT_BY_ID_SUCCESS',
  UPDATE_PRODUCT_BY_ID_FAILED = 'UPDATE_PRODUCT_BY_ID_FAILED',
  UNLOCK_PRODUCT_BY_ID = 'UNLOCK_PRODUCT_BY_ID',
  UNLOCK_PRODUCT_BY_ID_SUCCESS = 'UNLOCK_PRODUCT_BY_ID_SUCCESS',
  UNLOCK_PRODUCT_BY_ID_FAILED = 'UNLOCK_PRODUCT_BY_ID_FAILED',
  EXPORT_CASES_REPORT = 'EXPORT_CASES_REPORT',
  FETCH_CASE_SUMMARY_BY_CASE_ID = 'FETCH_CASE_SUMMARY_BY_CASE_ID',
  FETCH_CASE_SUMMARY_BY_CASE_ID_SUCCESS = 'FETCH_CASE_SUMMARY_BY_CASE_ID_SUCCESS',
  FETCH_CASE_SUMMARY_BY_CASE_ID_FAILED = 'FETCH_CASE_SUMMARY_BY_CASE_ID_FAILED',
  FETCH_USERS_ONGOING = 'FETCH_USERS_ONGOING',
  FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILED = 'FETCH_USERS_FAILED',
  FETCH_INVOICES_ONGOING = 'FETCH_INVOICES_ONGOING',
  FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS',
  FETCH_INVOICES_FAILED = 'FETCH_INVOICES_FAILED',
  FETCH_CASES_WITH_FULL_DETAILS_AS_ADMIN = 'FETCH_CASES_WITH_FULL_DETAILS_AS_ADMIN',
  FETCH_CASES_WITH_FULL_DETAILS_AS_ADMIN_SUCCESS = 'FETCH_CASES_WITH_FULL_DETAILS_AS_ADMIN_SUCCESS',
  FETCH_CASES_WITH_FULL_DETAILS_AS_ADMIN_FAILED = 'FETCH_CASES_WITH_FULL_DETAILS_AS_ADMIN_FAILED',
  FETCH_CASES_WITH_FULL_DETAILS = 'FETCH_CASES_WITH_FULL_DETAILS',
  FETCH_CASES_WITH_FULL_DETAILS_SUCCESS = 'FETCH_CASES_WITH_FULL_DETAILS_SUCCESS',
  FETCH_CASES_WITH_FULL_DETAILS_FAILED = 'FETCH_CASES_WITH_FULL_DETAILS_FAILED',
  FETCH_RECENT_CASES_WITH_FULL_DETAILS = 'FETCH_RECENT_CASES_WITH_FULL_DETAILS',
  FETCH_RECENT_CASES_WITH_FULL_DETAILS_SUCCESS = 'FETCH_RECENT_CASES_WITH_FULL_DETAILS_SUCCESS',
  FETCH_RECENT_CASES_WITH_FULL_DETAILS_FAILED = 'FETCH_RECENT_CASES_WITH_FULL_DETAILS_FAILED',
  FETCH_CLIENTS = 'FETCH_CLIENTS',
  FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS',
  FETCH_CLIENTS_FAILED = 'FETCH_CLIENTS_FAILED',
  FETCH_CLIENT_BY_CLIENT_ID_ONGOING = 'FETCH_CLIENT_BY_CLIENT_ID_ONGOING',
  FETCH_CLIENT_BY_CLIENT_ID_SUCCESS = 'FETCH_CLIENT_BY_CLIENT_ID_SUCCESS',
  FETCH_CLIENT_BY_CLIENT_ID_FAILED = 'FETCH_CLIENT_BY_CLIENT_ID_FAILED',
  ADMIN_FETCH_CASES = 'ADMIN_FETCH_CASES',
  ADMIN_FETCH_CASES_SUCCESS = 'ADMIN_FETCH_CASES_SUCCESS',
  ADMIN_FETCH_CASES_FAILED = 'ADMIN_FETCH_CASES_FAILED',
  CREATE_OR_UPDATE_CLIENT_ONGOING = 'CREATE_OR_UPDATE_CLIENT_ONGOING',
  CREATE_OR_UPDATE_CLIENT_SUCCESS = 'CREATE_OR_UPDATE_CLIENT_SUCCESS',
  CREATE_OR_UPDATE_CLIENT_FAILED = 'CREATE_OR_UPDATE_CLIENT_FAILED',
  INCREMENT_NUMBER_OF_FUNERAL_DIRECTOR_INVITE = 'INCREMENT_NUMBER_OF_FUNERAL_DIRECTOR_INVITE',
  DECREMENT_NUMBER_OF_FUNERAL_DIRECTOR_INVITE = 'DECREMENT_NUMBER_OF_FUNERAL_DIRECTOR_INVITE',
  RESTORE_ADMIN_INITIAL_STATE = 'RESTORE_ADMIN_INITIAL_STATE',
}

export type IPortalCase = IPortalCaseResponseItem & {
  noOfInvites?: number
  noOfImages?: number
}

export interface IAdminState {
  manageUsersPageState: {
    users: Array<IEulogiseUser>
    fetchingUsers: boolean
  }
  manageInvoicesPageState: {
    invoices: Array<IInvoice>
    fetchingInvoices: boolean
  }
  portalCasesPageState: {
    cases: Array<IPortalCase>
    fetchingCases: boolean
    fetchingRecentCases: boolean
  }

  viewAllCasesPageState: {
    cases: Array<ICase>
    fetchingCases: boolean
  }
  viewAllClientsPageState: {
    clients: Array<IEulogiseClient>
    fetchingClients: boolean
  }
  createNewClientPageState: {
    clientData: {
      clientTitle: string
      clientAddress: string
      clientLogo: string
      invitedFuneralDirectors: Array<IEulogiseUser>
    }
    fetchingData: boolean
    numberOfPendingInvite: number
  }
  createNewCasePageState: {}
  funeralDirectors: Array<IEulogiseUser>
}

export interface IAdminAction {
  type: AdminActionTypes
  payload?: IAdminActionPayload
}

export interface IAdminActionPayload {
  caseId?: string
  product?: EulogiseProduct
  productId?: string
  productData?: ICardProductData
  noOfInvites?: number
  noOfImages?: number
  items?:
    | Array<IEulogiseUser>
    | Array<ICase>
    | Array<IEulogiseClient>
    | Array<IInvoice>
  count?: number
  ref?: string
  updatedCase?: ICase
  arrangerId?: string
  arrangerName?: string
}
