import { IMemorialProductModel } from '../src/ts/database/types/MemorialProductModel.types'

export default [
  {
    content: {
      theme: 'reflection',
      pageSize: 'A5',
      pageOrientation: 'portrait',
      pageMargins: [30, 40],
      pages: [
        {
          borders: [
            {
              color: 'black',
              borderStyle: 'solid',
              thickness: '1px',
            },
          ],
          rows: [
            {
              id: 'u8943gkh',
              type: 'image',
              height: 334,
              data: {
                filepath:
                  'booklet/themes/example-images/rawpixel-423648-unsplash-cropped.jpg',
                alignment: 'center',
                width: 334,
                height: 334,
              },
            },
            {
              id: '09cuoe77',
              type: 'text',
              height: 66,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'bgrhm',
                      text: 'Eva Langmoore',
                      type: 'header-two',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [16, 0],
                width: 360,
                height: 34,
                alignment: 'center',
              },
            },
            {
              id: 'tjg3h0xm',
              type: 'text',
              height: 24,
              data: {
                content: {
                  blocks: [
                    {
                      key: '9hqe8',
                      text: '10 March 1954 - 10 January 2018',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 14,
                alignment: 'center',
              },
            },
            { id: 'ly14btcr', type: 'space', height: 30, data: { height: 30 } },
            {
              id: 'zc2139nx',
              type: 'text',
              height: 27,
              data: {
                content: {
                  blocks: [
                    {
                      key: '73pmq',
                      text: 'Service',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 17,
                alignment: 'center',
              },
            },
            {
              id: 'q3acuzqr',
              type: 'text',
              height: 28,
              data: {
                content: {
                  blocks: [
                    {
                      key: '3lipa',
                      text: 'Eastern Suburbs Memorial Park West Chapel',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '36l6i',
                      text: 'Monday 18 January 2018',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [0, 0],
                width: 360,
                height: 28,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 419.53,
          pageHeight: 595.28,
          contentHeight: 501,
          contentBoundaries: { width: 359.53, height: 515.28 },
          pageStyle: {
            width: 419.53,
            height: 595.28,
            paddingTop: 40,
            paddingBottom: 40,
            backgroundImage:
              "url('https://staging.media.eulogisememorials.com/booklet/borders/border-01.png')",
            backgroundSize: '419.53px 595.28px',
          },
        },
        {
          borders: [
            {
              color: 'black',
              borderStyle: 'solid',
              thickness: '1px 0',
            },
          ],
          rows: [
            {
              id: 'm9acv2mu',
              type: 'text',
              height: 38,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'dnmej',
                      text: 'Welcome',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'aeqnr',
                      text: 'Celebrant, Joshua Goodheart',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 28,
                alignment: 'center',
              },
            },
            { id: 'que9u0sj', type: 'space', height: 24, data: { height: 24 } },
            {
              id: 'pjyqu6ky',
              type: 'image',
              height: 240,
              data: {
                filepath:
                  'booklet/themes/example-images/reflection-booklet-p2-joao-silas-636902.jpg',
                alignment: 'center',
                width: 251,
                height: 189,
              },
            },
            { id: 'vn8n7cey', type: 'space', height: 33, data: { height: 33 } },
            {
              id: '075b3hdf',
              type: 'text',
              height: 38,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'av87k',
                      text: 'Ava Maria',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '8bk3r',
                      text: 'Sung by, Innes Heart',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 28,
                alignment: 'center',
              },
            },
            { id: 'zpxkusmu', type: 'space', height: 23, data: { height: 23 } },
            {
              id: 'fl8hb3hk',
              type: 'text',
              height: 36,
              data: {
                content: {
                  blocks: [
                    {
                      key: '9r81s',
                      text: 'Poem',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'fjcm6',
                      text: 'Reading by Lucinda Goodperson',
                      type: 'paragraph-two',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 26,
                alignment: 'center',
              },
            },
            { id: 'w5j413q1', type: 'space', height: 33, data: { height: 33 } },
            {
              id: '3q81kn56',
              type: 'text',
              height: 39,
              data: {
                content: {
                  blocks: [
                    {
                      key: '1eksu',
                      text: 'First Tribute',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'f61lr',
                      text: 'Georgie Goodperson',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5.5, 0],
                width: 360,
                height: 28,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 419.53,
          pageHeight: 595.28,
          contentHeight: 504,
          contentBoundaries: { width: 359.53, height: 515.28 },
          pageStyle: {
            width: 419.53,
            height: 595.28,
            paddingTop: 40,
            paddingBottom: 40,
            backgroundImage:
              "url('https://staging.media.eulogisememorials.com/booklet/borders/border-04.png')",
            backgroundSize: '419.53px 595.28px',
          },
        },
        {
          borders: [
            {
              color: 'black',
              borderStyle: 'solid',
              thickness: '1px 0',
            },
          ],
          rows: [
            {
              id: '69zlottc',
              type: 'text',
              height: 25,
              data: {
                content: {
                  blocks: [
                    {
                      key: '6o8ej',
                      text: 'The Lord’s Prayer',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 15,
                alignment: 'center',
              },
            },
            {
              id: 'k2df0sr6',
              type: 'text',
              height: 202,
              data: {
                content: {
                  blocks: [
                    {
                      key: '3bq1i',
                      text: 'Our Father who art in heaven',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'aiidg',
                      text: 'hallowed be thy name. ',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'bmdm2',
                      text: 'Thy kingdom come. ',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '1vdr6',
                      text: 'Thy will be done, ',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'drekf',
                      text: 'on Earth as it is in Heaven. ',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'ctuor',
                      text: 'Give us this day our daily bread; ',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'ct9pv',
                      text: 'and forgive us our trespasses, ',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'colfc',
                      text: 'as we forgive those who trespass against us; ',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'dd2mi',
                      text: 'and lead us not into temptation,',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '4k0lg',
                      text: ' but deliver us from evil.',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '6v74h',
                      text: '',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '31t8q',
                      text: 'For thine is the Kingdom,',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'et9as',
                      text: 'and the power, and the glory,',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '3p0fm',
                      text: 'for ever and ever',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'agct8',
                      text: 'Amen.',
                      type: 'unstyled',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [3.5, 0],
                width: 360,
                height: 195,
                alignment: 'center',
              },
            },
            { id: '5fm08h19', type: 'space', height: 24, data: { height: 24 } },
            {
              id: 'lwnxejm3',
              type: 'text',
              height: 59,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'f1veu',
                      text: 'Commital',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [22, 0],
                width: 360,
                height: 15,
                alignment: 'center',
              },
            },
            { id: 'o1ez5z66', type: 'space', height: 19, data: { height: 19 } },
            {
              id: 'azex3dsg',
              type: 'text',
              height: 18,
              data: {
                content: {
                  blocks: [
                    {
                      key: '4v7dg',
                      text: 'Eulogy',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [1.5, 0],
                width: 360,
                height: 15,
                alignment: 'center',
              },
            },
            {
              id: '8efn4vld',
              type: 'text',
              height: 23,
              data: {
                content: {
                  blocks: [
                    {
                      key: '6strl',
                      text: 'Simone Langmoore',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 13,
                alignment: 'center',
              },
            },
            { id: '3lw4vyp0', type: 'space', height: 19, data: { height: 19 } },
            {
              id: '1pwjbwsh',
              type: 'text',
              height: 52,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'ajkia',
                      text: 'Blessing and Dismissal',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [18.5, 0],
                width: 360,
                height: 15,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 419.53,
          pageHeight: 595.28,
          contentHeight: 441,
          contentBoundaries: { width: 359.53, height: 515.28 },
          pageStyle: {
            width: 419.53,
            height: 595.28,
            paddingTop: 40,
            paddingBottom: 40,
            backgroundImage:
              "url('https://staging.media.eulogisememorials.com/booklet/borders/border-04.png')",
            backgroundSize: '419.53px 595.28px',
          },
        },
        {
          borders: [
            {
              color: 'black',
              borderStyle: 'solid',
              thickness: '1px',
            },
          ],
          rows: [
            { id: 'y00ybamu', type: 'space', height: 18, data: { height: 18 } },
            {
              id: 'q4w9bbxf',
              type: 'image',
              height: 216,
              data: {
                filepath:
                  'booklet/themes/example-images/reflection-p4-lady-portrait.jpg',
                alignment: 'center',
                width: 340,
                height: 339,
              },
            },
            {
              id: '7s1kc6j0',
              type: 'text',
              height: 35,
              data: {
                content: {
                  blocks: [
                    {
                      key: '14qgd',
                      text: 'Always in our hearts',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [
                        { offset: 0, length: 20, style: 'ITALIC' },
                      ],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [10, 0],
                width: 360,
                height: 15,
                alignment: 'center',
              },
            },
            {
              id: 'i5ic1f7b',
              type: 'text',
              height: 28,
              data: {
                content: {
                  blocks: [
                    {
                      key: '5ghmb',
                      text: 'Appreciation',
                      type: 'header-four',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 18,
                alignment: 'center',
              },
            },
            {
              id: 'p8e5ebah',
              type: 'text',
              height: 75,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'bfhjj',
                      text: 'The family would like to thank you for your support',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'albga',
                      text: 'during this time of sadness. ',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'e3g8d',
                      text: '',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'edh',
                      text: 'Please join us at the Pacific Room, Intercontinental',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '39jr1',
                      text: 'Hotel for refreshments',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 65,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 419.53,
          pageHeight: 595.28,
          contentHeight: 372,
          contentBoundaries: { width: 359.53, height: 515.28 },
          pageStyle: {
            width: 419.53,
            height: 595.28,
            paddingTop: 40,
            paddingBottom: 40,
            backgroundImage:
              "url('https://staging.media.eulogisememorials.com/booklet/borders/border-01.png')",
            backgroundSize: '419.53px 595.28px',
          },
        },
      ],
    },
    updatedAt: 1595818165700,
    status: 'complete',
    createdAt: 1595818165700,
    id: 'c10216e3-31a4-4a58-8b97-0c6927090070',
    case: '5712eddd-7154-48d5-81e0-14cccb85f0b2',
    fileStatus: 'generated',
  },
  {
    content: {
      theme: 'linen',
      pageSize: 'A5',
      pageOrientation: 'portrait',
      pageMargins: [30, 40],
      pages: [
        {
          background: {
            image: {
              filepath:
                'booklet/themes/background-images/linen-booklet-background.jpg',
            },
          },
          rows: [
            {
              id: 'judcggdv',
              type: 'text',
              height: 22,
              data: {
                content: {
                  blocks: [
                    {
                      key: '2oih4',
                      text: 'In Loving Memory of the Life of',
                      type: 'paragraph-two',
                      depth: 0,
                      inlineStyleRanges: [
                        { offset: 0, length: 31, style: 'ITALIC' },
                      ],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 12,
                alignment: 'center',
              },
            },
            {
              id: 'eua58pfe',
              type: 'text',
              height: 60,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'cnf6f',
                      text: 'Dr Kimberly Davenport',
                      type: 'header-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [10.5, 0],
                width: 360,
                height: 39,
                alignment: 'center',
              },
            },
            {
              id: '0c5m4j1n',
              type: 'text',
              height: 22,
              data: {
                content: {
                  blocks: [
                    {
                      key: '6q9cl',
                      text: '10 March 1954 - 10 January 2018',
                      type: 'paragraph-two',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 12,
                alignment: 'center',
              },
            },
            { id: 'gkv3xlgf', type: 'space', height: 26, data: { height: 26 } },
            {
              id: 'o85j0etr',
              type: 'image',
              height: 293,
              data: {
                filepath:
                  'booklet/themes/example-images/daniil-kuzelev-492953-unsplash-cropped.jpg',
                alignment: 'center',
                width: 238,
                height: 293,
              },
            },
            { id: 'g02ew9j9', type: 'space', height: 26, data: { height: 26 } },
            {
              id: '5v2o38uf',
              type: 'text',
              height: 34,
              data: {
                content: {
                  blocks: [
                    {
                      key: '6lo4u',
                      text: 'You left us beautiful memories, your love is still our guide, ',
                      type: 'paragraph-two',
                      depth: 0,
                      inlineStyleRanges: [
                        { offset: 0, length: 62, style: 'ITALIC' },
                      ],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'ba6r0',
                      text: 'and although we can not see you, you are always at our side.',
                      type: 'paragraph-two',
                      depth: 0,
                      inlineStyleRanges: [
                        { offset: 0, length: 60, style: 'ITALIC' },
                      ],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 24,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 419.53,
          pageHeight: 595.28,
          contentHeight: 476,
          contentBoundaries: { width: 359.53, height: 515.28 },
          pageStyle: {
            width: 419.53,
            height: 595.28,
            paddingTop: 40,
            paddingBottom: 40,
            backgroundImage:
              "url('https://staging.media.eulogisememorials.com/booklet/themes/background-images/linen-booklet-background.jpg')",
            backgroundSize: '442.27px 618.02px',
          },
        },
        {
          rows: [
            { id: '5gcnh1rx', type: 'space', height: 46, data: { height: 46 } },
            {
              id: '7fpzbhoz',
              type: 'image',
              height: 200,
              data: {
                filepath:
                  'booklet/themes/example-images/linen-page-2-joao-2-images.jpg',
                alignment: 'center',
                width: 314,
                height: 200,
              },
            },
            { id: '5gdnh1rx', type: 'space', height: 5, data: { height: 5 } },
            {
              id: '4fpzbhoz',
              type: 'image',
              height: 237,
              data: {
                filepath:
                  'booklet/themes/example-images/jordan-bauer-274427-unsplash-linen.jpg',
                alignment: 'center',
                width: 314,
                height: 187,
              },
            },
            {
              id: 'uz3c5q0m',
              type: 'text',
              height: 22,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'ft13d',
                      text: 'Always in our hearts',
                      type: 'header-four',
                      depth: 0,
                      inlineStyleRanges: [
                        { offset: 0, length: 20, style: 'ITALIC' },
                      ],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [15, 0],
                width: 360,
                height: 11,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 419.53,
          pageHeight: 595.28,
          contentHeight: 510,
          contentBoundaries: { width: 359.53, height: 515.28 },
          pageStyle: {
            width: 419.53,
            height: 595.28,
            paddingTop: 40,
            paddingBottom: 40,
          },
        },
        {
          rows: [
            {
              id: 'g3ybn9tn',
              type: 'text',
              height: 18,
              data: {
                content: {
                  blocks: [
                    {
                      key: '9mo91',
                      text: 'Welcome',
                      type: 'header-four',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [0, 0],
                width: 360,
                height: 18,
                alignment: 'center',
              },
            },
            {
              id: '7awhb9n9',
              type: 'text',
              height: 23,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'edufq',
                      text: 'Celebrant, Joshua Goodheart',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 13,
                alignment: 'center',
              },
            },
            { id: 'qib8cour', type: 'space', height: 24, data: { height: 24 } },
            {
              id: 'h11koudn',
              type: 'text',
              height: 17,
              data: {
                content: {
                  blocks: [
                    {
                      key: '72v2h',
                      text: 'Hymn, Tears In Heaven',
                      type: 'header-four',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [-0.5, 0],
                width: 360,
                height: 18,
                alignment: 'center',
              },
            },
            {
              id: 'qgxlc9rn',
              type: 'text',
              height: 23,
              data: {
                content: {
                  blocks: [
                    {
                      key: '2pm4e',
                      text: 'Sung by, Ivan Angelheart',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 13,
                alignment: 'center',
              },
            },
            { id: 'kqsjcbmj', type: 'space', height: 24, data: { height: 24 } },
            {
              id: 'ds6bp5b8',
              type: 'text',
              height: 17,
              data: {
                content: {
                  blocks: [
                    {
                      key: '3so3u',
                      text: 'Poem, Poem Name',
                      type: 'header-four',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [-0.5, 0],
                width: 360,
                height: 18,
                alignment: 'center',
              },
            },
            {
              id: 'nuyje8jh',
              type: 'text',
              height: 23,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'f30t',
                      text: 'John Goodperson',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 13,
                alignment: 'center',
              },
            },
            { id: 'qc9kn8mt', type: 'space', height: 25, data: { height: 25 } },
            {
              id: '9cnyme64',
              type: 'text',
              height: 17,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'cs1ua',
                      text: 'First Tribute',
                      type: 'header-four',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [-0.5, 0],
                width: 360,
                height: 18,
                alignment: 'center',
              },
            },
            {
              id: 'g6bofg56',
              type: 'text',
              height: 23,
              data: {
                content: {
                  blocks: [
                    {
                      key: '6q58c',
                      text: 'Georgie Goodperson',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 13,
                alignment: 'center',
              },
            },
            { id: '1bhgpb30', type: 'space', height: 23, data: { height: 23 } },
            {
              id: 'rgyoxui9',
              type: 'text',
              height: 17,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'e0oec',
                      text: 'Second Tribute',
                      type: 'header-four',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [-0.5, 0],
                width: 360,
                height: 18,
                alignment: 'center',
              },
            },
            {
              id: 'nskvhs1o',
              type: 'text',
              height: 23,
              data: {
                content: {
                  blocks: [
                    {
                      key: '4j62j',
                      text: 'Lucinda Goodperson',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 13,
                alignment: 'center',
              },
            },
            { id: '9j86kcn8', type: 'space', height: 25, data: { height: 25 } },
            {
              id: '7ym29wbi',
              type: 'text',
              height: 17,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'bqtk4',
                      text: 'Address',
                      type: 'header-four',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [-0.5, 0],
                width: 360,
                height: 18,
                alignment: 'center',
              },
            },
            {
              id: '1z8ayrz8',
              type: 'text',
              height: 23,
              data: {
                content: {
                  blocks: [
                    {
                      key: '61f17',
                      text: 'Celebrant, Joshua Goodheart',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 13,
                alignment: 'center',
              },
            },
            { id: 'ee6jhyom', type: 'space', height: 27, data: { height: 27 } },
            {
              id: 'sl4tu191',
              type: 'text',
              height: 18,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'eao43',
                      text: 'Hymn, When September Ends',
                      type: 'header-four',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [0, 0],
                width: 360,
                height: 18,
                alignment: 'center',
              },
            },
            {
              id: 'p8q9bt2l',
              type: 'text',
              height: 23,
              data: {
                content: {
                  blocks: [
                    {
                      key: '75fu3',
                      text: 'Sung by, Ivan Angelheart',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 13,
                alignment: 'center',
              },
            },
            { id: 'gfjaj3ck', type: 'space', height: 23, data: { height: 23 } },
            {
              id: 'englrqf6',
              type: 'text',
              height: 28,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'vfr6',
                      text: 'Words of Farewell',
                      type: 'header-four',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 18,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 419.53,
          pageHeight: 595.28,
          contentHeight: 481,
          contentBoundaries: { width: 359.53, height: 515.28 },
          pageStyle: {
            width: 419.53,
            height: 595.28,
            paddingTop: 40,
            paddingBottom: 40,
          },
        },
        {
          background: {
            image: {
              filepath:
                'booklet/themes/background-images/linen-booklet-background.jpg',
            },
          },
          rows: [
            { id: 'drzbhqqy', type: 'space', height: 50, data: { height: 50 } },
            {
              id: '8syir7bg',
              type: 'image',
              height: 257,
              data: {
                filepath:
                  'booklet/themes/example-images/kinga-cichewicz-587833-unsplash.jpg',
                alignment: 'center',
                width: 360,
                height: 257,
              },
            },
            { id: 'ndpi1z2l', type: 'space', height: 41, data: { height: 41 } },
            {
              id: 'muzwt5um',
              type: 'text',
              height: 28,
              data: {
                content: {
                  blocks: [
                    {
                      key: '8i0g',
                      text: 'Appreciation',
                      type: 'header-four',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 18,
                alignment: 'center',
              },
            },
            {
              id: 'zaap2qqn',
              type: 'text',
              height: 75,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'a24o2',
                      text: 'The family would like to thank you for your support',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'adg8a',
                      text: 'during this time of sadness. ',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '9vm27',
                      text: '',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'evlmd',
                      text: 'Please join us at the Pacific Room, Intercontinental',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'dmvmu',
                      text: 'Hotel for refreshments',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 65,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 419.53,
          pageHeight: 595.28,
          contentHeight: 451,
          contentBoundaries: { width: 359.53, height: 515.28 },
          pageStyle: {
            width: 419.53,
            height: 595.28,
            paddingTop: 40,
            paddingBottom: 40,
            backgroundImage:
              "url('https://staging.media.eulogisememorials.com/booklet/themes/background-images/linen-booklet-background.jpg')",
            backgroundSize: '442.27px 618.02px',
          },
        },
      ],
    },
    createdAt: 1595818165700,
    id: 'f2219b62-d225-48b2-9059-3332d338f503',
    case: 'b565d16d-5567-4971-9250-4990cf6f16b2',
    updatedAt: 1595818165700,
    status: 'incomplete',
  },
  {
    content: {
      theme: 'grandeur',
      pageSize: 'A5',
      pageOrientation: 'portrait',
      pageMargins: [30, 40],
      pages: [{ rows: [] }, { rows: [] }, { rows: [] }, { rows: [] }],
    },
    createdAt: 1583276666257,
    id: '47e50e02-95ee-43bb-901e-e9cdb6ee3318',
    case: '75c93d2d-f7bf-46e7-9226-c74bfc28d531',
    updatedAt: 1583276666257,
    status: 'incomplete',
  },
] as Array<IMemorialProductModel.Schema>
