import { IMemorialProductModel } from '../src/ts/database/types/MemorialProductModel.types'

export default [
  {
    content: {
      theme: 'aura',
      pageSize: 'BOOKMARK',
      pageOrientation: 'portrait',
      pageMargins: [14, 40],
      pages: [{ rows: [] }, { rows: [] }, { rows: [] }, { rows: [] }],
    },
    createdAt: 1595818165700,
    id: 'fe589f54-1a63-4711-8579-85be16428868',
    case: '75c93d2d-f7bf-46e7-9226-c74bfc28d531',
    updatedAt: 1595818165700,
    status: 'incomplete',
  },
  {
    content: {
      theme: 'reflection',
      pageSize: 'BOOKMARK',
      pageOrientation: 'portrait',
      pageMargins: [14, 40],
      pages: [{ rows: [] }, { rows: [] }, { rows: [] }, { rows: [] }],
    },
    createdAt: 1595818165700,
    id: 'b5140523-2ae1-4ac6-9dbe-1849b9ab6527',
    case: 'b565d16d-5567-4971-9250-4990cf6f16b2',
    updatedAt: 1595818165700,
    status: 'incomplete',
  },
  {
    content: {
      theme: 'aura',
      pageSize: 'BOOKMARK',
      pageOrientation: 'portrait',
      pageMargins: [14, 40],
      pages: [
        {
          background: {
            image: {
              filepath: 'bookmark/themes/background-images/aura-front-bg.jpg',
            },
          },
          rows: [
            {
              id: '7f1sm3s9',
              type: 'text',
              height: 48,
              data: {
                content: {
                  blocks: [
                    {
                      key: '8hiqu',
                      text: 'In Loving Memory of the Life of',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 132,
                height: 38,
                alignment: 'center',
              },
            },
            {
              id: 'ry00ssf7',
              type: 'text',
              height: 53,
              data: {
                content: {
                  blocks: [
                    {
                      key: '4fg91',
                      text: 'Lisa Colby',
                      type: 'header-three',
                      depth: 0,
                      inlineStyleRanges: [
                        { offset: 0, length: 10, style: 'BOLD' },
                      ],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [10, 0],
                width: 132,
                height: 33,
                alignment: 'center',
              },
            },
            { id: '913g9tls', type: 'space', height: 15, data: { height: 15 } },
            {
              id: '7fpzbhoz',
              type: 'image',
              height: 129,
              data: {
                filepath: 'bookmark/themes/example-images/aura-profile.jpg',
                alignment: 'center',
                width: 129,
                height: 129,
              },
            },
            {
              id: 'q1og9tls',
              type: 'space',
              height: 320,
              data: { height: 320 },
            },
            {
              id: 'ekh9ybre',
              type: 'text',
              height: 48,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'bemo4',
                      text: '10 March 1954 - 10 January 2018',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 132,
                height: 38,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 160,
          pageHeight: 702,
          contentHeight: 553,
          contentBoundaries: { width: 132, height: 622 },
          pageStyle: {
            width: 160,
            height: 702,
            paddingTop: 40,
            paddingBottom: 40,
            backgroundImage:
              "url('https://staging.media.eulogisememorials.com/bookmark/themes/background-images/aura-front-bg.jpg')",
            backgroundSize: '182.74px 724.74px',
          },
        },
        {
          rows: [
            {
              id: 'g679s1in',
              type: 'text',
              height: 38,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'ca7a4',
                      text: 'Welcome',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '2vq1f',
                      text: 'Celebrant, Joshua Goodheart',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [3.5, 0],
                width: 132,
                height: 31,
                alignment: 'center',
              },
            },
            { id: 'huiguyck', type: 'space', height: 29, data: { height: 29 } },
            {
              id: '459jc2c1',
              type: 'image',
              height: 132,
              data: {
                filepath:
                  'booklet/themes/example-images/tracey-hocking-726156-unsplash-cropped.jpg',
                alignment: 'center',
                width: 132,
                height: 132,
              },
            },
            { id: 's5p73597', type: 'space', height: 34, data: { height: 34 } },
            {
              id: 'yo4kpivl',
              type: 'text',
              height: 45,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'a5oum',
                      text: 'Hymn, Abide With Me',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '8v22l',
                      text: 'Henry Francis Lyte',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [7, 0],
                width: 132,
                height: 31,
                alignment: 'center',
              },
            },
            { id: 'ngq08v75', type: 'space', height: 39, data: { height: 39 } },
            {
              id: 'gah0wvzv',
              type: 'text',
              height: 40,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'vs0n',
                      text: 'First Tribute',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'f8gds',
                      text: 'Georgie Goodperson',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [4.5, 0],
                width: 132,
                height: 31,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 160,
          pageHeight: 702,
          contentHeight: 357,
          contentBoundaries: { width: 132, height: 622 },
          pageStyle: {
            width: 160,
            height: 702,
            paddingTop: 40,
            paddingBottom: 40,
          },
        },
        {
          rows: [
            {
              id: 'g679s1in',
              type: 'text',
              height: 38,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'ca7a4',
                      text: 'Welcome',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '2vq1f',
                      text: 'Celebrant, Joshua Goodheart',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [3.5, 0],
                width: 132,
                height: 31,
                alignment: 'center',
              },
            },
            { id: 'huiguyck', type: 'space', height: 29, data: { height: 29 } },
            {
              id: '459jc2c1',
              type: 'image',
              height: 132,
              data: {
                filepath:
                  'booklet/themes/example-images/tracey-hocking-726156-unsplash-cropped.jpg',
                alignment: 'center',
                width: 132,
                height: 132,
              },
            },
            { id: 's5p73597', type: 'space', height: 34, data: { height: 34 } },
            {
              id: 'yo4kpivl',
              type: 'text',
              height: 45,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'a5oum',
                      text: 'Hymn, Abide With Me',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '8v22l',
                      text: 'Henry Francis Lyte',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [7, 0],
                width: 132,
                height: 31,
                alignment: 'center',
              },
            },
            { id: 'ngq08v75', type: 'space', height: 39, data: { height: 39 } },
            {
              id: 'gah0wvzv',
              type: 'text',
              height: 40,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'vs0n',
                      text: 'First Tribute',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'f8gds',
                      text: 'Georgie Goodperson',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [4.5, 0],
                width: 132,
                height: 31,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 160,
          pageHeight: 702,
          contentHeight: 357,
          contentBoundaries: { width: 132, height: 622 },
          pageStyle: {
            width: 160,
            height: 702,
            paddingTop: 40,
            paddingBottom: 40,
          },
        },
        {
          background: {
            image: {
              filepath: 'bookmark/themes/background-images/aura-back-bg.jpg',
            },
          },
          rows: [
            {
              id: '6umm86t6',
              type: 'space',
              height: 107,
              data: { height: 107 },
            },
            {
              id: 'm5l3n9qw',
              type: 'text',
              height: 29,
              data: {
                content: {
                  blocks: [
                    {
                      key: '241aq',
                      text: 'Love is Immortal',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [
                        { offset: 0, length: 16, style: 'BOLD' },
                      ],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 132,
                height: 19,
                alignment: 'center',
              },
            },
            {
              id: 'jth5itdq',
              type: 'text',
              height: 150,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'e5ib3',
                      text: 'Love is pure energy and',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'fbafv',
                      text: 'No matter how hard you try,',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'a0rlu',
                      text: 'You can never kill love',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'l7cr',
                      text: "Because pure energy can't die",
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '846gi',
                      text: 'The feeling of love can fade,',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '13cgi',
                      text: 'And the body can cease to give,',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '21vgi',
                      text: 'But the energy created by love',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '1xcgi',
                      text: 'Is immortal and continues',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'zhsgi',
                      text: 'To live',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 132,
                height: 140,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 160,
          pageHeight: 702,
          contentHeight: 318,
          contentBoundaries: { width: 132, height: 622 },
          pageStyle: {
            width: 160,
            height: 702,
            paddingTop: 40,
            paddingBottom: 40,
            backgroundImage:
              "url('https://staging.media.eulogisememorials.com/bookmark/themes/background-images/aura-back-bg.jpg')",
            backgroundSize: '182.74px 724.74px',
          },
        },
      ],
    },
    updatedAt: 1595818165700,
    status: 'complete',
    createdAt: 1595818165700,
    id: 'b2ecf46c-21ec-4bea-9f8c-7b014f9afbe2',
    case: '5712eddd-7154-48d5-81e0-14cccb85f0b2',
    fileStatus: 'generated',
  },
] as Array<IMemorialProductModel.Schema>
