import { IMemorialProductModel } from '../src/ts/database/types/MemorialProductModel.types'

export default [
  {
    content: {
      theme: 'aura',
      pageSize: 'A5',
      pageOrientation: 'portrait',
      pageMargins: [30, 40],
      pages: [
        {
          background: {
            image: {
              filepath:
                'booklet/themes/background-images/floral-faded-booklet-background-front.jpg',
            },
          },
          rows: [
            {
              id: '7f1sm3s9',
              type: 'text',
              height: 26,
              data: {
                content: {
                  blocks: [
                    {
                      key: '8hiqu',
                      text: 'In Loving Memory of the Life of',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 16,
                alignment: 'center',
              },
            },
            {
              id: 'ry00ssf7',
              type: 'text',
              height: 83,
              data: {
                content: {
                  blocks: [
                    {
                      key: '4fg91',
                      text: 'Lisa Colby',
                      type: 'header-two',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [10, 0],
                width: 360,
                height: 63,
                alignment: 'center',
              },
            },
            {
              id: 'ekh9ybre',
              type: 'text',
              height: 26,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'bemo4',
                      text: '10 March 1954 - 10 January 2018',
                      type: 'header-six',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 16,
                alignment: 'center',
              },
            },
            {
              id: 'q1og9tls',
              type: 'space',
              height: 312,
              data: { height: 312 },
            },
            {
              id: '4isdyvif',
              type: 'text',
              height: 26,
              data: {
                content: {
                  blocks: [
                    {
                      key: '9j9f5',
                      text: 'Service',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [
                        { offset: 0, length: 7, style: 'BOLD' },
                      ],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [3.5, 0],
                width: 360,
                height: 19,
                alignment: 'center',
              },
            },
            {
              id: 'ju8zsudx',
              type: 'text',
              height: 38,
              data: {
                content: {
                  blocks: [
                    {
                      key: '7rk74',
                      text: 'Eastern Suburbs Memorial Park West Chapel',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'e9s6f',
                      text: 'Monday 18 January 2018',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 28,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 419.53,
          pageHeight: 595.28,
          contentHeight: 490,
          contentBoundaries: { width: 359.53, height: 515.28 },
          pageStyle: {
            width: 419.53,
            height: 595.28,
            paddingTop: 40,
            paddingBottom: 40,
            backgroundImage:
              "url('https://staging.media.eulogisememorials.com/booklet/themes/background-images/floral-faded-booklet-background-front.jpg')",
            backgroundSize: '442.27px 618.02px',
          },
        },
        {
          rows: [
            {
              id: 'g679s1in',
              type: 'text',
              height: 38,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'ca7a4',
                      text: 'Welcome',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '2vq1f',
                      text: 'Celebrant, Joshua Goodheart',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [3.5, 0],
                width: 360,
                height: 31,
                alignment: 'center',
              },
            },
            { id: 'huiguyck', type: 'space', height: 29, data: { height: 29 } },
            {
              id: '459jc2c1',
              type: 'image',
              height: 232,
              data: {
                filepath:
                  'booklet/themes/example-images/tracey-hocking-726156-unsplash-cropped.jpg',
                alignment: 'center',
                width: 232,
                height: 232,
              },
            },
            { id: 's5p73597', type: 'space', height: 34, data: { height: 34 } },
            {
              id: 'yo4kpivl',
              type: 'text',
              height: 45,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'a5oum',
                      text: 'Hymn, Abide With Me',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '8v22l',
                      text: 'Henry Francis Lyte',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [7, 0],
                width: 360,
                height: 31,
                alignment: 'center',
              },
            },
            { id: 'ngq08v75', type: 'space', height: 39, data: { height: 39 } },
            {
              id: 'gah0wvzv',
              type: 'text',
              height: 40,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'vs0n',
                      text: 'First Tribute',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'f8gds',
                      text: 'Georgie Goodperson',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [4.5, 0],
                width: 360,
                height: 31,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 419.53,
          pageHeight: 595.28,
          contentHeight: 457,
          contentBoundaries: { width: 359.53, height: 515.28 },
          pageStyle: {
            width: 419.53,
            height: 595.28,
            paddingTop: 40,
            paddingBottom: 40,
          },
        },
        {
          rows: [
            {
              id: '536ss092',
              type: 'text',
              height: 41,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'c5136',
                      text: 'Second Tribute',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'fif52',
                      text: 'Lucinda Goodperson',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 31,
                alignment: 'center',
              },
            },
            { id: 'zopx0hhq', type: 'space', height: 15, data: { height: 15 } },
            {
              id: '9o9oefmb',
              type: 'text',
              height: 21,
              data: {
                content: {
                  blocks: [
                    {
                      key: '1hj7m',
                      text: 'The Lord’s Prayer',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [1.5, 0],
                width: 360,
                height: 18,
                alignment: 'center',
              },
            },
            {
              id: 'z7m6hjvs',
              type: 'text',
              height: 205,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'fljno',
                      text: 'Our Father who art in heaven',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'q68t',
                      text: 'hallowed be thy name. ',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'em4dc',
                      text: 'Thy kingdom come. ',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '4jn94',
                      text: 'Thy will be done, ',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '7v2ok',
                      text: 'on Earth as it is in Heaven. ',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '7t8td',
                      text: 'Give us this day our daily bread; ',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '7dt25',
                      text: 'and forgive us our trespasses, ',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '8qp8q',
                      text: 'as we forgive those who trespass against us; ',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'a2uka',
                      text: 'and lead us not into temptation,',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '1pidd',
                      text: ' but deliver us from evil.',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'egeg1',
                      text: '',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'cn3c6',
                      text: 'For thine is the Kingdom,',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '573il',
                      text: 'and the power, and the glory,',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '3tl4h',
                      text: 'for ever and ever',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '2b15o',
                      text: 'Amen.',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 195,
                alignment: 'center',
              },
            },
            { id: '7pyy8cbt', type: 'space', height: 15, data: { height: 15 } },
            {
              id: 'fmquatjk',
              type: 'text',
              height: 28,
              data: {
                content: {
                  blocks: [
                    {
                      key: '52j9h',
                      text: 'Address',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 18,
                alignment: 'center',
              },
            },
            {
              id: 'fb5am67l',
              type: 'text',
              height: 18,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'fjjtu',
                      text: 'Celebrant, Joshua Goodheart',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [2.5, 0],
                width: 360,
                height: 13,
                alignment: 'center',
              },
            },
            {
              id: 'n7v3cemy',
              type: 'text',
              height: 90,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'sd1t',
                      text: 'Hymn, When September Ends',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [42, 0],
                width: 360,
                height: 18,
                alignment: 'center',
              },
            },
            {
              id: 'h9inp3rf',
              type: 'text',
              height: 25,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'eon4m',
                      text: 'Words of Farewell',
                      type: 'header-five',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [3.5, 0],
                width: 360,
                height: 18,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 419.53,
          pageHeight: 595.28,
          contentHeight: 458,
          contentBoundaries: { width: 359.53, height: 515.28 },
          pageStyle: {
            width: 419.53,
            height: 595.28,
            paddingTop: 40,
            paddingBottom: 40,
          },
        },
        {
          background: {
            image: {
              filepath:
                'booklet/themes/background-images/floral-solid-booklet-background-back.jpg',
            },
          },
          rows: [
            { id: '6umm86t6', type: 'space', height: 28, data: { height: 28 } },
            {
              id: 'm5l3n9qw',
              type: 'text',
              height: 43,
              data: {
                content: {
                  blocks: [
                    {
                      key: '241aq',
                      text: 'Thank you',
                      type: 'header-three',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 33,
                alignment: 'center',
              },
            },
            {
              id: 'jth5itdq',
              type: 'text',
              height: 80,
              data: {
                content: {
                  blocks: [
                    {
                      key: 'e5ib3',
                      text: 'The family would like to thank you for your support',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'fbafv',
                      text: 'during this time of sadness. ',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'a0rlu',
                      text: '',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: 'l7cr',
                      text: 'Please join us at the Pacific Room, Intercontinental',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                    {
                      key: '846gi',
                      text: 'Hotel for refreshments',
                      type: 'paragraph-one',
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                style: 'unstyled',
                margin: [5, 0],
                width: 360,
                height: 70,
                alignment: 'center',
              },
            },
          ],
          pageWidth: 419.53,
          pageHeight: 595.28,
          contentHeight: 144,
          contentBoundaries: { width: 359.53, height: 515.28 },
          pageStyle: {
            width: 419.53,
            height: 595.28,
            paddingTop: 40,
            paddingBottom: 40,
            backgroundImage:
              "url('https://staging.media.eulogisememorials.com/booklet/themes/background-images/floral-solid-booklet-background-back.jpg')",
            backgroundSize: '442.27px 618.02px',
          },
        },
      ],
    },
    updatedAt: 1622896588081,
    status: 'complete',
    createdAt: 1622896588081,
    id: 'ae9a42eb-6c70-46ae-8952-08a3ae1d36e7',
    case: '75c93d2d-f7bf-46e7-9226-c74bfc28d531',
    fileStatus: 'generated',
  },
] as Array<IMemorialProductModel.Schema>
