import { ITransactionModel } from '../src/ts/database/types/TransactionModel.types'

export default [
  {
    createdAt: 1622896588081,
    customer: 'ee14274a-b251-4f65-9236-15a67d51c43a',
    stripePaymentIntentId: 'ch_1DnBAsL0vfllQFYixrtAgc4e',
    id: 'c759a691-a373-4a13-85bd-8ea210432105',
    stripePaymentIntentData: {
      id: 'ch_1DnBAsL0vfllQFYixrtAgc4e',
      object: 'charge',
      amount: 9900,
      amount_refunded: 0,
      application: null,
      application_fee: null,
      balance_transaction: 'txn_1DnBAsL0vfllQFYiaFsm89NN',
      captured: true,
      created: 1546202778,
      currency: 'aud',
      customer: null,
      description: 'Eulogise reference: 51e2bf06-208a-48c7-be5a-5f0798e36989',
      destination: null,
      dispute: null,
      failure_code: null,
      failure_message: null,
      fraud_details: {},
      invoice: null,
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      order: null,
      outcome: {
        network_status: 'approved_by_network',
        reason: null,
        risk_level: 'normal',
        risk_score: 17,
        seller_message: 'Payment complete.',
        type: 'authorized',
      },
      paid: true,
      payment_intent: null,
      receipt_email: null,
      receipt_number: null,
      refunded: false,
      refunds: {
        object: 'list',
        data: [],
        has_more: false,
        total_count: 0,
        url: '/v1/charges/ch_1DnBAsL0vfllQFYixrtAgc4e/refunds',
      },
      review: null,
      shipping: null,
      source: {
        id: 'card_1DnBArL0vfllQFYiBlda2pE1',
        object: 'card',
        address_city: null,
        address_country: null,
        address_line1: null,
        address_line1_check: null,
        address_line2: null,
        address_state: null,
        address_zip: null,
        address_zip_check: null,
        brand: 'Visa',
        country: 'US',
        customer: null,
        cvc_check: 'pass',
        dynamic_last4: null,
        exp_month: 12,
        exp_year: 2022,
        funding: 'credit',
        last4: '4242',
        metadata: {},
        name: 'sh',
        tokenization_method: null,
      },
      source_transfer: null,
      statement_descriptor: null,
      status: 'succeeded',
      transfer_group: null,
    },
    updatedAt: 1622896588081,
  },
  {
    createdAt: 1622896588081,
    customer: '7b1a9791-9365-4ec9-b9bc-6ad0e05afa1a',
    stripePaymentIntentId: 'ch_1DlrtaL0vfllQFYiqVKfGzUm',
    id: '9c484c53-9e94-4c0f-8ac4-9bace2bddb46',
    stripePaymentIntentData: {
      id: 'ch_1DlrtaL0vfllQFYiqVKfGzUm',
      object: 'charge',
      amount: 27200,
      amount_refunded: 0,
      application: null,
      application_fee: null,
      balance_transaction: 'txn_1DlrtaL0vfllQFYibgxnhu8o',
      captured: true,
      created: 1545890342,
      currency: 'aud',
      customer: null,
      description: 'Eugloise reference: 30fe2a31-69e5-499a-b6dd-a9a1be1862e5',
      destination: null,
      dispute: null,
      failure_code: null,
      failure_message: null,
      fraud_details: {},
      invoice: null,
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      order: null,
      outcome: {
        network_status: 'approved_by_network',
        reason: null,
        risk_level: 'normal',
        risk_score: 19,
        seller_message: 'Payment complete.',
        type: 'authorized',
      },
      paid: true,
      payment_intent: null,
      receipt_email: null,
      receipt_number: null,
      refunded: false,
      refunds: {
        object: 'list',
        data: [],
        has_more: false,
        total_count: 0,
        url: '/v1/charges/ch_1DlrtaL0vfllQFYiqVKfGzUm/refunds',
      },
      review: null,
      shipping: null,
      source: {
        id: 'card_1DlrtZL0vfllQFYi0or6KMBh',
        object: 'card',
        address_city: null,
        address_country: null,
        address_line1: null,
        address_line1_check: null,
        address_line2: null,
        address_state: null,
        address_zip: null,
        address_zip_check: null,
        brand: 'Visa',
        country: 'US',
        customer: null,
        cvc_check: 'pass',
        dynamic_last4: null,
        exp_month: 12,
        exp_year: 2022,
        funding: 'credit',
        last4: '4242',
        metadata: {},
        name: 'John Cena',
        tokenization_method: null,
      },
      source_transfer: null,
      statement_descriptor: null,
      status: 'succeeded',
      transfer_group: null,
    },
    updatedAt: 1622896588081,
  },
  {
    createdAt: 1622896588081,
    customer: '5f9a4e33-1457-455d-bcc7-21198602067a',
    stripePaymentIntentId: 'ch_1DrEW7L0vfllQFYiUHOlmO1e',
    id: '969f593b-545d-44fb-856f-dde024da7cf2',
    stripePaymentIntentData: {
      id: 'ch_1DrEW7L0vfllQFYiUHOlmO1e',
      object: 'charge',
      amount: 27200,
      amount_refunded: 0,
      application: null,
      application_fee: null,
      application_fee_amount: null,
      balance_transaction: 'txn_1DrEW7L0vfllQFYichWJfbAa',
      captured: true,
      created: 1547168939,
      currency: 'aud',
      customer: null,
      description: 'Eulogise reference: a01e7efc-fd23-4a05-beed-68f6ec6981b2',
      destination: null,
      dispute: null,
      failure_code: null,
      failure_message: null,
      fraud_details: {},
      invoice: null,
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      order: null,
      outcome: {
        network_status: 'approved_by_network',
        reason: null,
        risk_level: 'normal',
        risk_score: 9,
        seller_message: 'Payment complete.',
        type: 'authorized',
      },
      paid: true,
      payment_intent: null,
      receipt_email: null,
      receipt_number: null,
      refunded: false,
      refunds: {
        object: 'list',
        data: [],
        has_more: false,
        total_count: 0,
        url: '/v1/charges/ch_1DrEW7L0vfllQFYiUHOlmO1e/refunds',
      },
      review: null,
      shipping: null,
      source: {
        id: 'card_1DrEW1L0vfllQFYivMrAAcnU',
        object: 'card',
        address_city: null,
        address_country: null,
        address_line1: null,
        address_line1_check: null,
        address_line2: null,
        address_state: null,
        address_zip: null,
        address_zip_check: null,
        brand: 'Visa',
        country: 'US',
        customer: null,
        cvc_check: 'pass',
        dynamic_last4: null,
        exp_month: 2,
        exp_year: 2020,
        funding: 'credit',
        last4: '4242',
        metadata: {},
        name: 'sh',
        tokenization_method: null,
      },
      source_transfer: null,
      statement_descriptor: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null,
    },
    updatedAt: 1622896588081,
  },
] as Array<ITransactionModel.Schema>
