import { ICardProductBackgroundImageBase } from '@eulogise/core'

export const MOCK_BACKGROUND_IMAGES: Array<ICardProductBackgroundImageBase> = [
  { id: 'Mountains', name: 'Mountains', categoryIds: ['scenic'] },
  { id: 'Uluru', name: 'Uluru', categoryIds: ['australian'] },
  { id: 'Field', name: 'Field', categoryIds: ['scenic'] },
  { id: 'Clouds', name: 'Clouds', categoryIds: ['skies_sunsets'] },
  { id: 'Lavender', name: 'Lavender', categoryIds: ['scenic'] },
  { id: 'Light_Rays', name: 'Light Rays', categoryIds: ['skies_sunsets'] },
  {
    id: 'Sunset_Cross',
    name: 'Sunset Cross',
    categoryIds: ['religion_culture'],
  },
  { id: 'Fall_Leaves', name: 'Fall Leaves', categoryIds: ['scenic'] },
  { id: 'Purple_Roses', name: 'Purple Roses', categoryIds: ['floral'] },
  { id: 'Rosemary', name: 'Rosemary', categoryIds: ['floral'] },
  { id: 'Pier', name: 'Pier', categoryIds: ['scenic'] },
  { id: 'Golf', name: 'Golf', categoryIds: ['activities_hobbies'] },
  { id: 'Sailing', name: 'Sailing', categoryIds: ['activities_hobbies'] },
  {
    id: 'United_States_Flag',
    name: 'United States Flag',
    categoryIds: ['american'],
  },
  {
    id: 'Ski_Mountain',
    name: 'Ski Mountain',
    categoryIds: ['activities_hobbies'],
  },
  { id: 'Snowing', name: 'Snowing', categoryIds: ['scenic'] },
  { id: 'Cloudy_Sky', name: 'Cloudy Sky', categoryIds: ['skies_sunsets'] },
  { id: 'Italian_Fields', name: 'Italian Fields', categoryIds: ['scenic'] },
  { id: 'Snow_Drops', name: 'Snow Drops', categoryIds: ['floral'] },
  { id: 'Meadow', name: 'Meadow', categoryIds: ['scenic'] },
  { id: 'Beach', name: 'Beach', categoryIds: ['popular'] },
  { id: 'Floral', name: 'Floral', categoryIds: ['floral'] },
  { id: 'Linen', name: 'Linen', categoryIds: ['popular', 'textures'] },
  { id: 'Paper', name: 'Paper', categoryIds: ['popular', 'textures'] },
  { id: 'Calm_Beach', name: 'Calm Beach', categoryIds: ['scenic'] },
  { id: 'Blue_Gum', name: 'Blue Gum', categoryIds: ['australian'] },
  {
    id: 'Cloudy_Mountain',
    name: 'Cloudy Mountain',
    categoryIds: ['skies_sunsets'],
  },
  { id: 'Floral_Painting', name: 'Floral Painting', categoryIds: ['floral'] },
  { id: 'Botanical', name: 'Botanical', categoryIds: ['floral'] },
  { id: 'Pastel_Beige', name: 'Pastel Beige', categoryIds: ['textures'] },
  { id: 'Pastel_Green', name: 'Pastel Green', categoryIds: ['textures'] },
  { id: 'Pastel_Pink', name: 'Pastel Pink', categoryIds: ['textures'] },
  { id: 'Pastel_Purple', name: 'Pastel Purple', categoryIds: ['textures'] },
  { id: 'Pastel_Blue', name: 'Pastel Blue', categoryIds: ['textures'] },
  { id: 'Gold_Roses', name: 'Gold Roses', categoryIds: ['floral'] },
  {
    id: 'Blue_Pastel_Flowers',
    name: 'Blue Pastel Flowers',
    categoryIds: ['floral'],
  },
  { id: 'Fall_Flowers', name: 'Fall Flowers', categoryIds: ['floral'] },
  { id: 'flower_memorial', name: 'Flower Memorial', categoryIds: ['floral'] },
  {
    id: 'Sailing_Watercolor',
    name: 'Sailing Watercolor',
    categoryIds: ['activities_hobbies'],
  },
  {
    id: 'Blue_Stripe',
    name: 'Blue Stripe',
    categoryIds: ['popular'],
  },
  {
    id: 'Ocean_Shore',
    name: 'Ocean Shore',
    categoryIds: ['activities_hobbies'],
  },
  {
    id: 'Stars_And_Stripes',
    name: 'Stars And Stripes',
    categoryIds: ['american'],
  },
  {
    id: 'Statue_Of_Liberty',
    name: 'Statue Of Liberty',
    categoryIds: ['american'],
  },
  { id: 'USA_Paper', name: 'USA Paper', categoryIds: ['american'] },
  {
    id: 'Australian_Watercolour',
    name: 'Australian Watercolour',
    categoryIds: ['australian'],
  },
  {
    id: 'Mountain_Watercolor',
    name: 'Mountain Watercolor',
    categoryIds: ['scenic'],
  },
  {
    id: 'Hill_Cross',
    name: 'Hill Cross',
    categoryIds: ['religion_culture'],
  },
  { id: 'Paper_2', name: 'Paper 2', categoryIds: ['textures'] },
]
