import { ISlideshowTheme } from '@eulogise/core'

const oldTheme: Array<ISlideshowTheme> = [
  {
    id: 'aura',
    title: 'Aura',
    oldThemeName: 'contemporary',
    image: 'slideshow/themes/preview-images/contemporary.jpg',
    description:
      'A gentle theme with each new image sharpening from a blur to full focus, in a combination of full frame images and true to ratio pictures.',
    content: {
      themeDefaultImageFilter: 'none',
      slideshowTransitionIn: 'crossBlur',
      slideshowTransitionOut: 'crossFade',
      slideshowBackground: {
        color: 'ghostwhite',
        image: {
          filepath: 'slideshow/themes/title-slide-images/Aura/aura-basic.jpg',
        },
        enlarge: [true],
      },
      slideBackground: {
        getImage: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        blurred: [false],
      },
      image: {
        animation: ['none'],
        layout: ['frame'],
      },
      text: {
        style: {
          color: '#000000',
          textAlign: 'center',
        },
        layers: {
          title: {
            style: {
              fontSize: '40px',
              fontWeight: 'normal',
              fontFamily: 'Sacramento',
              margin: '10px 0px 10px 0px',
              letterSpacing: '1.78px',
            },
          },
          subTitle: {
            style: {
              fontFamily: 'Josefin Sans',
              fontSize: '20px',
              fontWeight: '300',
              fontStretch: 'normal',
              lineHeight: 'normal',
              letterSpacing: '1px',
            },
          },
        },
        animation: 'none',
        transitionIn: 'slideUp',
        transitionOut: 'crossBlur',
        endSlideTransitionIn: 'crossBlur',
        endSlideTransitionOut: 'slideDown',
      },
      transition: [
        'blurOutToBgFadeIn',
        'blurOutToBgSlideUp',
        'blurOutToBgSlideRight',
      ],
      transitionDuration: 2000,
    },
  },
  {
    id: 'grandeur',
    title: 'Grandeur',
    oldThemeName: 'nostalgia',
    image: 'slideshow/themes/preview-images/nostalgia.jpg',
    description:
      'A sequence of softly enlarging images against a soft defocused background. The picture motion alternates between slide show and carousel animations.',
    content: {
      themeDefaultImageFilter: 'none',
      slideshowTransitionIn: 'crossFade',
      slideshowTransitionOut: 'crossFade',
      slideshowBackground: {
        color: 'ghostwhite',
        image: {
          filepath:
            'slideshow/themes/title-slide-images/Grandeur/grandeur-basic.jpg',
        },
      },
      slideBackground: {
        getImage: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        blurred: [false],
      },
      image: {
        animation: ['none'],
        layout: ['inset'],
      },
      text: {
        style: {
          color: '#4a4a4a',
          fontFamily: 'Lora',
          textAlign: 'center',
          fontWeight: 'normal',
          fontStyle: 'normal',
          lineHeight: 'normal',
          letterSpacing: '1.26px',
        },
        layers: {
          title: {
            style: {
              fontSize: '32px',
              fontWeight: 'noraml',
              fontStyle: 'normal',
              margin: '0px 0px 25px 0px',
            },
          },
          subTitle: {
            style: {
              fontSize: '22px',
              fontStyle: 'normal',
              letterSpacing: '1.86px',
            },
          },
        },
        animation: 'none',
        transitionIn: 'slideUp',
        transitionOut: 'crossBlur',
        endSlideTransitionIn: 'crossBlur',
        endSlideTransitionOut: 'slideDown',
      },
      transition: [
        'blurOutToBgFadeIn',
        'blurOutToBgSlideUp',
        'blurOutToBgSlideRight',
      ],
      transitionDuration: 2000,
    },
  },
  {
    id: 'linen',
    title: 'Linen',
    oldThemeName: 'linen',
    image: 'slideshow/themes/preview-images/linen.jpg',
    description:
      'A smooth carousel animation of framed pictures on a linen background, evoking the mood of a photo album.',
    content: {
      themeDefaultImageFilter: 'none',
      slideshowTransitionIn: 'none',
      slideshowTransitionOut: 'crossFade',
      slideshowBackground: {
        color: 'whitesmoke',
        image: {
          filepath: 'slideshow/themes/title-slide-images/Linen/linen-basic.jpg',
        },
      },
      slideBackground: {
        getImage: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        blurred: [false],
      },
      image: {
        animation: [
          'zoomIn',
          'zoomIn',
          'zoomOut',
          'zoomIn',
          'zoomOut',
          'zoomIn',
          'zoomOut',
          'zoomIn',
          'zoomOut',
          'zoomIn',
          'zoomOut',
          'none',
        ],
        layout: ['frame'],
      },
      text: {
        style: {
          color: '#4a4a4a',
          fontFamily: 'Lora',
          textAlign: 'center',
          lineHeight: '1.4',
        },
        layers: {
          title: {
            style: {
              fontSize: '36px',
              fontFamily: 'Lora',
              textAlign: 'center',
              lineHeight: '1.4',
              margin: '10px 0px 10px 0px',
            },
          },
          subTitle: {
            style: {
              fontSize: '26px',
              fontStyle: 'italic',
              fontFamily: 'Lora',
            },
          },
        },
        animation: 'none',
        transitionIn: 'slideUp',
        transitionOut: 'crossBlur',
        endSlideTransitionIn: 'crossBlur',
        endSlideTransitionOut: 'slideDown',
      },
      transition: [
        'crossFade',
        'crossFade',
        'slideLeft',
        'crossFade',
        'crossFade',
        'slideUp',
        'crossFade',
        'crossFade',
        'slideRight',
        'crossFade',
        'crossFade',
        'slideDown',
      ],
      transitionDuration: 2000,
    },
  },
  {
    id: 'reflection',
    title: 'Refliction',
    oldThemeName: 'nostalgia',
    image: 'slideshow/themes/preview-images/nostalgia.jpg',
    description:
      'A sequence of softly enlarging images against a soft defocused background. The picture motion alternates between slide show and carousel animations.',
    content: {
      themeDefaultImageFilter: 'none',
      slideshowTransitionIn: 'crossFade',
      slideshowTransitionOut: 'crossFade',
      slideBackground: {
        getImage: ['next'],
        blurred: [true],
      },
      image: {
        animation: [
          'zoomOut',
          'zoomIn',
          'zoomOut',
          'zoomIn',
          'slideRight',
          'slideRight',
          'slideRight',
          'zoomIn',
          'zoomIn',
          'zoomIn',
          'slideRight',
          'slideRight',
          'slideRight',
        ],
        layout: ['inset'],
      },
      text: {
        style: {
          color: '#ffffff',
          textAlign: 'center',
        },
        layers: {
          title: {
            style: {
              fontFamily: 'Lora',
              fontSize: '40px',
              fontWeight: 'normal',
              margin: '10px 0px 10px 0px',
            },
          },
          subTitle: {
            style: {
              fontSize: '18px',
              fontStyle: 'normal',
              letterSpacing: '0.4px',
              fontFamily: 'Montserrat',
            },
          },
        },
        animation: 'none',
        transitionIn: 'slideUp',
        transitionOut: 'crossBlur',
        endSlideTransitionIn: 'crossBlur',
        endSlideTransitionOut: 'slideDown',
      },
      transition: [
        'crossBlur',
        'crossBlur',
        'crossBlur',
        'wipeLeftFadeIn',
        'wipeLeftFadeIn',
        'wipeLeftFadeIn',
        'crossBlur',
        'wipeLeftFadeIn',
        'wipeLeftFadeIn',
        'wipeLeftFadeIn',
        'wipeLeftFadeIn',
        'wipeLeftFadeIn',
        'blurOutToBgFadeIn',
      ],
      transitionDuration: 2000,
    },
  },
  {
    id: 'classic',
    title: 'Classic',
    oldThemeName: 'simplicity',
    image: 'slideshow/themes/preview-images/simplicity.jpg',
    description:
      'A gentle sequence of animations from one image to the next, alternating between a slideshow and carousel effect.',
    content: {
      themeDefaultImageFilter: 'none',
      slideshowTransitionIn: 'crossFade',
      slideshowTransitionOut: 'crossFade',
      slideshowBackground: {
        color: 'ghostwhite',
        image: {
          filepath:
            'slideshow/themes/title-slide-images/Classic/classic-basic.jpg',
        },
      },
      slideBackground: {
        getImage: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        blurred: [false],
      },
      image: {
        animation: ['zoomIn'],
        layout: ['frame'],
      },
      text: {
        style: {
          color: '#4a4a4a',
          fontFamily: 'Courgette',
          textAlign: 'center',
        },
        layers: {
          title: {
            style: {
              fontWeight: 'normal',
              fontSize: '40px',
              margin: '10px 0px 10px 0px',
            },
          },
          subTitle: {
            style: {
              fontFamily: 'Playfair Display',
              fontSize: '23px',
            },
          },
        },
        animation: 'none',
        transitionIn: 'crossFadeZoomOut',
        transitionOut: 'crossBlur',
        endSlideTransitionIn: 'crossBlur',
        endSlideTransitionOut: 'slideDown',
      },
      transition: [
        'crossFadeZoomOut',
        'crossFadeZoomOut',
        'crossFadeZoomOut',
        'slideRight',
        'slideRight',
      ],
      transitionDuration: 2000,
    },
  },
  {
    id: 'grace',
    title: 'Grace',
    oldThemeName: 'classic',
    image: 'slideshow/themes/preview-images/classic.jpg',
    description:
      'A higher energy theme with an over exposure transition between full frame images and a fade on effect for a carousel animation.',
    content: {
      themeDefaultImageFilter: 'inkwell',
      slideshowTransitionIn: 'none',
      slideshowTransitionOut: 'slideRight',
      slideBackground: {
        getImage: ['next'],
        blurred: [true],
      },
      image: {
        animation: [
          'zoomIn',
          'zoomOut',
          'zoomIn',
          'zoomOut',
          'slideRight',
          'slideRight',
          'zoomIn',
          'zoomOut',
          'zoomIn',
          'zoomOut',
          'zoomIn',
          'slideLeft',
          'slideLeft',
          'slideLeft',
        ],
        layout: [
          'fill',
          'fit',
          'fill',
          'fit',
          'insetShadow',
          'insetShadow',
          'insetShadow',
          'fit',
          'fill',
          'fit',
          'fit',
          'insetShadow',
          'insetShadow',
          'insetShadow',
        ],
      },
      text: {
        style: {
          color: 'white',
          textAlign: 'center',
        },
        layers: {
          title: {
            style: {
              fontSize: '50px',
              fontWeight: 'normal',
              margin: '10px 0px 10px 0px',
              fontFamily: 'Pinyon Script',
            },
          },
          subTitle: {
            style: {
              fontSize: '17px',
              fontStyle: 'normal',
              fontFamily: 'Playfair Display',
              letterSpacing: '0.56px',
            },
          },
        },
        animation: 'none',
        transitionIn: 'slideUp',
        transitionOut: 'crossBlur',
        endSlideTransitionIn: 'crossBlur',
        endSlideTransitionOut: 'slideDown',
      },
      transition: [
        'crossFade',
        'crossFade',
        'crossFade',
        'crossFade',
        'slideRight',
        'slideRight',
        'slideRight',
        'crossFlash',
        'crossFlash',
        'crossFlash',
        'crossFlash',
        'crossFlash',
        'slideLeft',
        'slideLeft',
      ],
      transitionDuration: 2000,
    },
  },
]

export default oldTheme
